[2023-08-22 15:38:41,942] logger_util.py->write_log line:61 [INFO] 
-------------接口请求开始-----------
[2023-08-22 15:38:41,942] logger_util.py->write_log line:61 [INFO] 接口名称：modbus协议下发-保存寄存器有符号8位整型
[2023-08-22 15:38:41,942] logger_util.py->write_log line:61 [INFO] 接口方式：post
[2023-08-22 15:38:41,942] logger_util.py->write_log line:61 [INFO] 接口路径：http://127.0.0.1:6700/v1/cms/io/write
[2023-08-22 15:38:41,942] logger_util.py->write_log line:61 [INFO] 请求头：{'Content-Type': 'application/json'}
[2023-08-22 15:38:41,942] logger_util.py->write_log line:61 [INFO] 请求参数：{'tagDatas': {'MOD_SINT1': '-11'}}
[2023-08-22 15:38:41,943] logger_util.py->write_log line:61 [INFO] 文件上传：None
[2023-08-22 15:38:43,977] logger_util.py->error_log line:65 [INFO] 断言失败:status_code不等于200
[2023-08-22 15:38:43,977] logger_util.py->write_log line:61 [INFO] 接口请求失败！
[2023-08-22 15:38:43,977] logger_util.py->write_log line:61 [INFO] -------------接口请求结束-----------

[2023-08-22 15:38:43,978] logger_util.py->error_log line:65 [INFO] 断言异常：异常信息: Traceback (most recent call last):
  File "E:\Project_python\api_cms\common\requests_util.py", line 347, in validate_result
    error_log("断言失败:"+assert_key+"不等于"+str(assert_value))
  File "E:\Project_python\api_cms\common\logger_util.py", line 66, in error_log
    raise Exception(log_message)
Exception: 断言失败:status_code不等于200

[2023-08-22 15:38:43,978] logger_util.py->error_log line:65 [INFO] 分析YAML文件异常：异常信息: Traceback (most recent call last):
  File "E:\Project_python\api_cms\common\requests_util.py", line 347, in validate_result
    error_log("断言失败:"+assert_key+"不等于"+str(assert_value))
  File "E:\Project_python\api_cms\common\logger_util.py", line 66, in error_log
    raise Exception(log_message)
Exception: 断言失败:status_code不等于200

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\Project_python\api_cms\common\requests_util.py", line 249, in analysis_yaml
    self.validate_result(yq_result, return_text, status_code)
  File "E:\Project_python\api_cms\common\requests_util.py", line 401, in validate_result
    error_log("断言异常：异常信息: %s" % str(traceback.format_exc()))
  File "E:\Project_python\api_cms\common\logger_util.py", line 66, in error_log
    raise Exception(log_message)
Exception: 断言异常：异常信息: Traceback (most recent call last):
  File "E:\Project_python\api_cms\common\requests_util.py", line 347, in validate_result
    error_log("断言失败:"+assert_key+"不等于"+str(assert_value))
  File "E:\Project_python\api_cms\common\logger_util.py", line 66, in error_log
    raise Exception(log_message)
Exception: 断言失败:status_code不等于200


[2023-08-22 15:38:44,074] logger_util.py->write_log line:61 [INFO] 
-------------接口请求开始-----------
[2023-08-22 15:38:44,075] logger_util.py->write_log line:61 [INFO] 接口名称：modbus协议下发-保存寄存器有符号16位整型
[2023-08-22 15:38:44,075] logger_util.py->write_log line:61 [INFO] 接口方式：post
[2023-08-22 15:38:44,075] logger_util.py->write_log line:61 [INFO] 接口路径：http://127.0.0.1:6700/v1/cms/io/write
[2023-08-22 15:38:44,075] logger_util.py->write_log line:61 [INFO] 请求头：{'Content-Type': 'application/json'}
[2023-08-22 15:38:44,075] logger_util.py->write_log line:61 [INFO] 请求参数：{'tagDatas': {'MOD_INT1': '22'}}
[2023-08-22 15:38:44,075] logger_util.py->write_log line:61 [INFO] 文件上传：None
[2023-08-22 15:38:46,104] logger_util.py->error_log line:65 [INFO] 断言失败:status_code不等于200
[2023-08-22 15:38:46,104] logger_util.py->write_log line:61 [INFO] 接口请求失败！
[2023-08-22 15:38:46,104] logger_util.py->write_log line:61 [INFO] -------------接口请求结束-----------

[2023-08-22 15:38:46,104] logger_util.py->error_log line:65 [INFO] 断言异常：异常信息: Traceback (most recent call last):
  File "E:\Project_python\api_cms\common\requests_util.py", line 347, in validate_result
    error_log("断言失败:"+assert_key+"不等于"+str(assert_value))
  File "E:\Project_python\api_cms\common\logger_util.py", line 66, in error_log
    raise Exception(log_message)
Exception: 断言失败:status_code不等于200

[2023-08-22 15:38:46,104] logger_util.py->error_log line:65 [INFO] 分析YAML文件异常：异常信息: Traceback (most recent call last):
  File "E:\Project_python\api_cms\common\requests_util.py", line 347, in validate_result
    error_log("断言失败:"+assert_key+"不等于"+str(assert_value))
  File "E:\Project_python\api_cms\common\logger_util.py", line 66, in error_log
    raise Exception(log_message)
Exception: 断言失败:status_code不等于200

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\Project_python\api_cms\common\requests_util.py", line 249, in analysis_yaml
    self.validate_result(yq_result, return_text, status_code)
  File "E:\Project_python\api_cms\common\requests_util.py", line 401, in validate_result
    error_log("断言异常：异常信息: %s" % str(traceback.format_exc()))
  File "E:\Project_python\api_cms\common\logger_util.py", line 66, in error_log
    raise Exception(log_message)
Exception: 断言异常：异常信息: Traceback (most recent call last):
  File "E:\Project_python\api_cms\common\requests_util.py", line 347, in validate_result
    error_log("断言失败:"+assert_key+"不等于"+str(assert_value))
  File "E:\Project_python\api_cms\common\logger_util.py", line 66, in error_log
    raise Exception(log_message)
Exception: 断言失败:status_code不等于200


[2023-08-22 15:38:46,129] logger_util.py->write_log line:61 [INFO] 
-------------接口请求开始-----------
[2023-08-22 15:38:46,130] logger_util.py->write_log line:61 [INFO] 接口名称：modbus协议下发-保存寄存器有符号32位整型
[2023-08-22 15:38:46,130] logger_util.py->write_log line:61 [INFO] 接口方式：post
[2023-08-22 15:38:46,130] logger_util.py->write_log line:61 [INFO] 接口路径：http://127.0.0.1:6700/v1/cms/io/write
[2023-08-22 15:38:46,130] logger_util.py->write_log line:61 [INFO] 请求头：{'Content-Type': 'application/json'}
[2023-08-22 15:38:46,130] logger_util.py->write_log line:61 [INFO] 请求参数：{'tagDatas': {'MOD_DINT1': '33'}}
[2023-08-22 15:38:46,130] logger_util.py->write_log line:61 [INFO] 文件上传：None
[2023-08-22 15:38:48,155] logger_util.py->error_log line:65 [INFO] 断言失败:status_code不等于200
[2023-08-22 15:38:48,156] logger_util.py->write_log line:61 [INFO] 接口请求失败！
[2023-08-22 15:38:48,156] logger_util.py->write_log line:61 [INFO] -------------接口请求结束-----------

[2023-08-22 15:38:48,156] logger_util.py->error_log line:65 [INFO] 断言异常：异常信息: Traceback (most recent call last):
  File "E:\Project_python\api_cms\common\requests_util.py", line 347, in validate_result
    error_log("断言失败:"+assert_key+"不等于"+str(assert_value))
  File "E:\Project_python\api_cms\common\logger_util.py", line 66, in error_log
    raise Exception(log_message)
Exception: 断言失败:status_code不等于200

[2023-08-22 15:38:48,156] logger_util.py->error_log line:65 [INFO] 分析YAML文件异常：异常信息: Traceback (most recent call last):
  File "E:\Project_python\api_cms\common\requests_util.py", line 347, in validate_result
    error_log("断言失败:"+assert_key+"不等于"+str(assert_value))
  File "E:\Project_python\api_cms\common\logger_util.py", line 66, in error_log
    raise Exception(log_message)
Exception: 断言失败:status_code不等于200

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\Project_python\api_cms\common\requests_util.py", line 249, in analysis_yaml
    self.validate_result(yq_result, return_text, status_code)
  File "E:\Project_python\api_cms\common\requests_util.py", line 401, in validate_result
    error_log("断言异常：异常信息: %s" % str(traceback.format_exc()))
  File "E:\Project_python\api_cms\common\logger_util.py", line 66, in error_log
    raise Exception(log_message)
Exception: 断言异常：异常信息: Traceback (most recent call last):
  File "E:\Project_python\api_cms\common\requests_util.py", line 347, in validate_result
    error_log("断言失败:"+assert_key+"不等于"+str(assert_value))
  File "E:\Project_python\api_cms\common\logger_util.py", line 66, in error_log
    raise Exception(log_message)
Exception: 断言失败:status_code不等于200


[2023-08-22 15:38:48,181] logger_util.py->write_log line:61 [INFO] 
-------------接口请求开始-----------
[2023-08-22 15:38:48,181] logger_util.py->write_log line:61 [INFO] 接口名称：modbus协议下发-保存寄存器无符号8位整型
[2023-08-22 15:38:48,181] logger_util.py->write_log line:61 [INFO] 接口方式：post
[2023-08-22 15:38:48,181] logger_util.py->write_log line:61 [INFO] 接口路径：http://127.0.0.1:6700/v1/cms/io/write
[2023-08-22 15:38:48,181] logger_util.py->write_log line:61 [INFO] 请求头：{'Content-Type': 'application/json'}
[2023-08-22 15:38:48,181] logger_util.py->write_log line:61 [INFO] 请求参数：{'tagDatas': {'MOD_USINT1': '44'}}
[2023-08-22 15:38:48,181] logger_util.py->write_log line:61 [INFO] 文件上传：None
[2023-08-22 15:38:50,210] logger_util.py->error_log line:65 [INFO] 断言失败:status_code不等于200
[2023-08-22 15:38:50,211] logger_util.py->write_log line:61 [INFO] 接口请求失败！
[2023-08-22 15:38:50,211] logger_util.py->write_log line:61 [INFO] -------------接口请求结束-----------

[2023-08-22 15:38:50,211] logger_util.py->error_log line:65 [INFO] 断言异常：异常信息: Traceback (most recent call last):
  File "E:\Project_python\api_cms\common\requests_util.py", line 347, in validate_result
    error_log("断言失败:"+assert_key+"不等于"+str(assert_value))
  File "E:\Project_python\api_cms\common\logger_util.py", line 66, in error_log
    raise Exception(log_message)
Exception: 断言失败:status_code不等于200

[2023-08-22 15:38:50,211] logger_util.py->error_log line:65 [INFO] 分析YAML文件异常：异常信息: Traceback (most recent call last):
  File "E:\Project_python\api_cms\common\requests_util.py", line 347, in validate_result
    error_log("断言失败:"+assert_key+"不等于"+str(assert_value))
  File "E:\Project_python\api_cms\common\logger_util.py", line 66, in error_log
    raise Exception(log_message)
Exception: 断言失败:status_code不等于200

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\Project_python\api_cms\common\requests_util.py", line 249, in analysis_yaml
    self.validate_result(yq_result, return_text, status_code)
  File "E:\Project_python\api_cms\common\requests_util.py", line 401, in validate_result
    error_log("断言异常：异常信息: %s" % str(traceback.format_exc()))
  File "E:\Project_python\api_cms\common\logger_util.py", line 66, in error_log
    raise Exception(log_message)
Exception: 断言异常：异常信息: Traceback (most recent call last):
  File "E:\Project_python\api_cms\common\requests_util.py", line 347, in validate_result
    error_log("断言失败:"+assert_key+"不等于"+str(assert_value))
  File "E:\Project_python\api_cms\common\logger_util.py", line 66, in error_log
    raise Exception(log_message)
Exception: 断言失败:status_code不等于200


[2023-08-22 15:38:50,236] logger_util.py->write_log line:61 [INFO] 
-------------接口请求开始-----------
[2023-08-22 15:38:50,236] logger_util.py->write_log line:61 [INFO] 接口名称：modbus协议下发-保存寄存器无符号16位整型
[2023-08-22 15:38:50,236] logger_util.py->write_log line:61 [INFO] 接口方式：post
[2023-08-22 15:38:50,236] logger_util.py->write_log line:61 [INFO] 接口路径：http://127.0.0.1:6700/v1/cms/io/write
[2023-08-22 15:38:50,236] logger_util.py->write_log line:61 [INFO] 请求头：{'Content-Type': 'application/json'}
[2023-08-22 15:38:50,236] logger_util.py->write_log line:61 [INFO] 请求参数：{'tagDatas': {'MOD_UINT1': '55'}}
[2023-08-22 15:38:50,236] logger_util.py->write_log line:61 [INFO] 文件上传：None
[2023-08-22 15:38:52,606] logger_util.py->error_log line:65 [INFO] 断言失败:status_code不等于200
[2023-08-22 15:38:52,607] logger_util.py->write_log line:61 [INFO] 接口请求失败！
[2023-08-22 15:38:52,607] logger_util.py->write_log line:61 [INFO] -------------接口请求结束-----------

[2023-08-22 15:38:52,607] logger_util.py->error_log line:65 [INFO] 断言异常：异常信息: Traceback (most recent call last):
  File "E:\Project_python\api_cms\common\requests_util.py", line 347, in validate_result
    error_log("断言失败:"+assert_key+"不等于"+str(assert_value))
  File "E:\Project_python\api_cms\common\logger_util.py", line 66, in error_log
    raise Exception(log_message)
Exception: 断言失败:status_code不等于200

[2023-08-22 15:38:52,607] logger_util.py->error_log line:65 [INFO] 分析YAML文件异常：异常信息: Traceback (most recent call last):
  File "E:\Project_python\api_cms\common\requests_util.py", line 347, in validate_result
    error_log("断言失败:"+assert_key+"不等于"+str(assert_value))
  File "E:\Project_python\api_cms\common\logger_util.py", line 66, in error_log
    raise Exception(log_message)
Exception: 断言失败:status_code不等于200

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\Project_python\api_cms\common\requests_util.py", line 249, in analysis_yaml
    self.validate_result(yq_result, return_text, status_code)
  File "E:\Project_python\api_cms\common\requests_util.py", line 401, in validate_result
    error_log("断言异常：异常信息: %s" % str(traceback.format_exc()))
  File "E:\Project_python\api_cms\common\logger_util.py", line 66, in error_log
    raise Exception(log_message)
Exception: 断言异常：异常信息: Traceback (most recent call last):
  File "E:\Project_python\api_cms\common\requests_util.py", line 347, in validate_result
    error_log("断言失败:"+assert_key+"不等于"+str(assert_value))
  File "E:\Project_python\api_cms\common\logger_util.py", line 66, in error_log
    raise Exception(log_message)
Exception: 断言失败:status_code不等于200


[2023-08-22 15:38:52,632] logger_util.py->write_log line:61 [INFO] 
-------------接口请求开始-----------
[2023-08-22 15:38:52,633] logger_util.py->write_log line:61 [INFO] 接口名称：modbus协议下发-保存寄存器无符号32位整型
[2023-08-22 15:38:52,633] logger_util.py->write_log line:61 [INFO] 接口方式：post
[2023-08-22 15:38:52,633] logger_util.py->write_log line:61 [INFO] 接口路径：http://127.0.0.1:6700/v1/cms/io/write
[2023-08-22 15:38:52,633] logger_util.py->write_log line:61 [INFO] 请求头：{'Content-Type': 'application/json'}
[2023-08-22 15:38:52,633] logger_util.py->write_log line:61 [INFO] 请求参数：{'tagDatas': {'MOD_UDINT1': '66'}}
[2023-08-22 15:38:52,633] logger_util.py->write_log line:61 [INFO] 文件上传：None
[2023-08-22 15:38:54,658] logger_util.py->error_log line:65 [INFO] 断言失败:status_code不等于200
[2023-08-22 15:38:54,659] logger_util.py->write_log line:61 [INFO] 接口请求失败！
[2023-08-22 15:38:54,659] logger_util.py->write_log line:61 [INFO] -------------接口请求结束-----------

[2023-08-22 15:38:54,659] logger_util.py->error_log line:65 [INFO] 断言异常：异常信息: Traceback (most recent call last):
  File "E:\Project_python\api_cms\common\requests_util.py", line 347, in validate_result
    error_log("断言失败:"+assert_key+"不等于"+str(assert_value))
  File "E:\Project_python\api_cms\common\logger_util.py", line 66, in error_log
    raise Exception(log_message)
Exception: 断言失败:status_code不等于200

[2023-08-22 15:38:54,659] logger_util.py->error_log line:65 [INFO] 分析YAML文件异常：异常信息: Traceback (most recent call last):
  File "E:\Project_python\api_cms\common\requests_util.py", line 347, in validate_result
    error_log("断言失败:"+assert_key+"不等于"+str(assert_value))
  File "E:\Project_python\api_cms\common\logger_util.py", line 66, in error_log
    raise Exception(log_message)
Exception: 断言失败:status_code不等于200

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\Project_python\api_cms\common\requests_util.py", line 249, in analysis_yaml
    self.validate_result(yq_result, return_text, status_code)
  File "E:\Project_python\api_cms\common\requests_util.py", line 401, in validate_result
    error_log("断言异常：异常信息: %s" % str(traceback.format_exc()))
  File "E:\Project_python\api_cms\common\logger_util.py", line 66, in error_log
    raise Exception(log_message)
Exception: 断言异常：异常信息: Traceback (most recent call last):
  File "E:\Project_python\api_cms\common\requests_util.py", line 347, in validate_result
    error_log("断言失败:"+assert_key+"不等于"+str(assert_value))
  File "E:\Project_python\api_cms\common\logger_util.py", line 66, in error_log
    raise Exception(log_message)
Exception: 断言失败:status_code不等于200


[2023-08-22 15:38:54,684] logger_util.py->write_log line:61 [INFO] 
-------------接口请求开始-----------
[2023-08-22 15:38:54,684] logger_util.py->write_log line:61 [INFO] 接口名称：modbus协议下发-保存寄存器F32位浮点数IEEE754
[2023-08-22 15:38:54,684] logger_util.py->write_log line:61 [INFO] 接口方式：post
[2023-08-22 15:38:54,684] logger_util.py->write_log line:61 [INFO] 接口路径：http://127.0.0.1:6700/v1/cms/io/write
[2023-08-22 15:38:54,684] logger_util.py->write_log line:61 [INFO] 请求头：{'Content-Type': 'application/json'}
[2023-08-22 15:38:54,685] logger_util.py->write_log line:61 [INFO] 请求参数：{'tagDatas': {'MOD_REAL1': '77.456'}}
[2023-08-22 15:38:54,685] logger_util.py->write_log line:61 [INFO] 文件上传：None
[2023-08-22 15:38:57,009] logger_util.py->error_log line:65 [INFO] 断言失败:status_code不等于200
[2023-08-22 15:38:57,010] logger_util.py->write_log line:61 [INFO] 接口请求失败！
[2023-08-22 15:38:57,010] logger_util.py->write_log line:61 [INFO] -------------接口请求结束-----------

[2023-08-22 15:38:57,010] logger_util.py->error_log line:65 [INFO] 断言异常：异常信息: Traceback (most recent call last):
  File "E:\Project_python\api_cms\common\requests_util.py", line 347, in validate_result
    error_log("断言失败:"+assert_key+"不等于"+str(assert_value))
  File "E:\Project_python\api_cms\common\logger_util.py", line 66, in error_log
    raise Exception(log_message)
Exception: 断言失败:status_code不等于200

[2023-08-22 15:38:57,010] logger_util.py->error_log line:65 [INFO] 分析YAML文件异常：异常信息: Traceback (most recent call last):
  File "E:\Project_python\api_cms\common\requests_util.py", line 347, in validate_result
    error_log("断言失败:"+assert_key+"不等于"+str(assert_value))
  File "E:\Project_python\api_cms\common\logger_util.py", line 66, in error_log
    raise Exception(log_message)
Exception: 断言失败:status_code不等于200

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\Project_python\api_cms\common\requests_util.py", line 249, in analysis_yaml
    self.validate_result(yq_result, return_text, status_code)
  File "E:\Project_python\api_cms\common\requests_util.py", line 401, in validate_result
    error_log("断言异常：异常信息: %s" % str(traceback.format_exc()))
  File "E:\Project_python\api_cms\common\logger_util.py", line 66, in error_log
    raise Exception(log_message)
Exception: 断言异常：异常信息: Traceback (most recent call last):
  File "E:\Project_python\api_cms\common\requests_util.py", line 347, in validate_result
    error_log("断言失败:"+assert_key+"不等于"+str(assert_value))
  File "E:\Project_python\api_cms\common\logger_util.py", line 66, in error_log
    raise Exception(log_message)
Exception: 断言失败:status_code不等于200


[2023-08-22 15:38:57,035] logger_util.py->write_log line:61 [INFO] 
-------------接口请求开始-----------
[2023-08-22 15:38:57,035] logger_util.py->write_log line:61 [INFO] 接口名称：modbus协议下发-保存寄存器二进制变量1
[2023-08-22 15:38:57,036] logger_util.py->write_log line:61 [INFO] 接口方式：post
[2023-08-22 15:38:57,036] logger_util.py->write_log line:61 [INFO] 接口路径：http://127.0.0.1:6700/v1/cms/io/write
[2023-08-22 15:38:57,036] logger_util.py->write_log line:61 [INFO] 请求头：{'Content-Type': 'application/json'}
[2023-08-22 15:38:57,036] logger_util.py->write_log line:61 [INFO] 请求参数：{'tagDatas': {'MOD_BOOL1': '1'}}
[2023-08-22 15:38:57,036] logger_util.py->write_log line:61 [INFO] 文件上传：None
[2023-08-22 15:38:59,421] logger_util.py->error_log line:65 [INFO] 断言失败:status_code不等于200
[2023-08-22 15:38:59,421] logger_util.py->write_log line:61 [INFO] 接口请求失败！
[2023-08-22 15:38:59,421] logger_util.py->write_log line:61 [INFO] -------------接口请求结束-----------

[2023-08-22 15:38:59,421] logger_util.py->error_log line:65 [INFO] 断言异常：异常信息: Traceback (most recent call last):
  File "E:\Project_python\api_cms\common\requests_util.py", line 347, in validate_result
    error_log("断言失败:"+assert_key+"不等于"+str(assert_value))
  File "E:\Project_python\api_cms\common\logger_util.py", line 66, in error_log
    raise Exception(log_message)
Exception: 断言失败:status_code不等于200

[2023-08-22 15:38:59,421] logger_util.py->error_log line:65 [INFO] 分析YAML文件异常：异常信息: Traceback (most recent call last):
  File "E:\Project_python\api_cms\common\requests_util.py", line 347, in validate_result
    error_log("断言失败:"+assert_key+"不等于"+str(assert_value))
  File "E:\Project_python\api_cms\common\logger_util.py", line 66, in error_log
    raise Exception(log_message)
Exception: 断言失败:status_code不等于200

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\Project_python\api_cms\common\requests_util.py", line 249, in analysis_yaml
    self.validate_result(yq_result, return_text, status_code)
  File "E:\Project_python\api_cms\common\requests_util.py", line 401, in validate_result
    error_log("断言异常：异常信息: %s" % str(traceback.format_exc()))
  File "E:\Project_python\api_cms\common\logger_util.py", line 66, in error_log
    raise Exception(log_message)
Exception: 断言异常：异常信息: Traceback (most recent call last):
  File "E:\Project_python\api_cms\common\requests_util.py", line 347, in validate_result
    error_log("断言失败:"+assert_key+"不等于"+str(assert_value))
  File "E:\Project_python\api_cms\common\logger_util.py", line 66, in error_log
    raise Exception(log_message)
Exception: 断言失败:status_code不等于200


[2023-08-22 15:38:59,448] logger_util.py->write_log line:61 [INFO] 
-------------接口请求开始-----------
[2023-08-22 15:38:59,448] logger_util.py->write_log line:61 [INFO] 接口名称：modbus协议下发-保存寄存器二进制变量2
[2023-08-22 15:38:59,448] logger_util.py->write_log line:61 [INFO] 接口方式：post
[2023-08-22 15:38:59,448] logger_util.py->write_log line:61 [INFO] 接口路径：http://127.0.0.1:6700/v1/cms/io/write
[2023-08-22 15:38:59,448] logger_util.py->write_log line:61 [INFO] 请求头：{'Content-Type': 'application/json'}
[2023-08-22 15:38:59,448] logger_util.py->write_log line:61 [INFO] 请求参数：{'tagDatas': {'MOD_BOOL2': '0'}}
[2023-08-22 15:38:59,449] logger_util.py->write_log line:61 [INFO] 文件上传：None
[2023-08-22 15:39:01,709] logger_util.py->error_log line:65 [INFO] 断言失败:status_code不等于200
[2023-08-22 15:39:01,710] logger_util.py->write_log line:61 [INFO] 接口请求失败！
[2023-08-22 15:39:01,710] logger_util.py->write_log line:61 [INFO] -------------接口请求结束-----------

[2023-08-22 15:39:01,710] logger_util.py->error_log line:65 [INFO] 断言异常：异常信息: Traceback (most recent call last):
  File "E:\Project_python\api_cms\common\requests_util.py", line 347, in validate_result
    error_log("断言失败:"+assert_key+"不等于"+str(assert_value))
  File "E:\Project_python\api_cms\common\logger_util.py", line 66, in error_log
    raise Exception(log_message)
Exception: 断言失败:status_code不等于200

[2023-08-22 15:39:01,710] logger_util.py->error_log line:65 [INFO] 分析YAML文件异常：异常信息: Traceback (most recent call last):
  File "E:\Project_python\api_cms\common\requests_util.py", line 347, in validate_result
    error_log("断言失败:"+assert_key+"不等于"+str(assert_value))
  File "E:\Project_python\api_cms\common\logger_util.py", line 66, in error_log
    raise Exception(log_message)
Exception: 断言失败:status_code不等于200

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\Project_python\api_cms\common\requests_util.py", line 249, in analysis_yaml
    self.validate_result(yq_result, return_text, status_code)
  File "E:\Project_python\api_cms\common\requests_util.py", line 401, in validate_result
    error_log("断言异常：异常信息: %s" % str(traceback.format_exc()))
  File "E:\Project_python\api_cms\common\logger_util.py", line 66, in error_log
    raise Exception(log_message)
Exception: 断言异常：异常信息: Traceback (most recent call last):
  File "E:\Project_python\api_cms\common\requests_util.py", line 347, in validate_result
    error_log("断言失败:"+assert_key+"不等于"+str(assert_value))
  File "E:\Project_python\api_cms\common\logger_util.py", line 66, in error_log
    raise Exception(log_message)
Exception: 断言失败:status_code不等于200


[2023-08-22 15:39:01,736] logger_util.py->write_log line:61 [INFO] 
-------------接口请求开始-----------
[2023-08-22 15:39:01,736] logger_util.py->write_log line:61 [INFO] 接口名称：modbus协议下发-保存寄存器字符串
[2023-08-22 15:39:01,736] logger_util.py->write_log line:61 [INFO] 接口方式：post
[2023-08-22 15:39:01,737] logger_util.py->write_log line:61 [INFO] 接口路径：http://127.0.0.1:6700/v1/cms/io/write
[2023-08-22 15:39:01,737] logger_util.py->write_log line:61 [INFO] 请求头：{'Content-Type': 'application/json'}
[2023-08-22 15:39:01,737] logger_util.py->write_log line:61 [INFO] 请求参数：{'tagDatas': {'MOD_STRING1': '文本1'}}
[2023-08-22 15:39:01,737] logger_util.py->write_log line:61 [INFO] 文件上传：None
[2023-08-22 15:39:04,111] logger_util.py->error_log line:65 [INFO] 断言失败:status_code不等于200
[2023-08-22 15:39:04,112] logger_util.py->write_log line:61 [INFO] 接口请求失败！
[2023-08-22 15:39:04,112] logger_util.py->write_log line:61 [INFO] -------------接口请求结束-----------

[2023-08-22 15:39:04,112] logger_util.py->error_log line:65 [INFO] 断言异常：异常信息: Traceback (most recent call last):
  File "E:\Project_python\api_cms\common\requests_util.py", line 347, in validate_result
    error_log("断言失败:"+assert_key+"不等于"+str(assert_value))
  File "E:\Project_python\api_cms\common\logger_util.py", line 66, in error_log
    raise Exception(log_message)
Exception: 断言失败:status_code不等于200

[2023-08-22 15:39:04,112] logger_util.py->error_log line:65 [INFO] 分析YAML文件异常：异常信息: Traceback (most recent call last):
  File "E:\Project_python\api_cms\common\requests_util.py", line 347, in validate_result
    error_log("断言失败:"+assert_key+"不等于"+str(assert_value))
  File "E:\Project_python\api_cms\common\logger_util.py", line 66, in error_log
    raise Exception(log_message)
Exception: 断言失败:status_code不等于200

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\Project_python\api_cms\common\requests_util.py", line 249, in analysis_yaml
    self.validate_result(yq_result, return_text, status_code)
  File "E:\Project_python\api_cms\common\requests_util.py", line 401, in validate_result
    error_log("断言异常：异常信息: %s" % str(traceback.format_exc()))
  File "E:\Project_python\api_cms\common\logger_util.py", line 66, in error_log
    raise Exception(log_message)
Exception: 断言异常：异常信息: Traceback (most recent call last):
  File "E:\Project_python\api_cms\common\requests_util.py", line 347, in validate_result
    error_log("断言失败:"+assert_key+"不等于"+str(assert_value))
  File "E:\Project_python\api_cms\common\logger_util.py", line 66, in error_log
    raise Exception(log_message)
Exception: 断言失败:status_code不等于200


[2023-08-22 15:39:04,137] logger_util.py->write_log line:61 [INFO] 
-------------接口请求开始-----------
[2023-08-22 15:39:04,137] logger_util.py->write_log line:61 [INFO] 接口名称：modbus协议下发-离散二进制变量
[2023-08-22 15:39:04,137] logger_util.py->write_log line:61 [INFO] 接口方式：post
[2023-08-22 15:39:04,137] logger_util.py->write_log line:61 [INFO] 接口路径：http://127.0.0.1:6700/v1/cms/io/write
[2023-08-22 15:39:04,137] logger_util.py->write_log line:61 [INFO] 请求头：{'Content-Type': 'application/json'}
[2023-08-22 15:39:04,137] logger_util.py->write_log line:61 [INFO] 请求参数：{'tagDatas': {'MOD_Q0': '1'}}
[2023-08-22 15:39:04,137] logger_util.py->write_log line:61 [INFO] 文件上传：None
[2023-08-22 15:39:06,511] logger_util.py->error_log line:65 [INFO] 断言失败:status_code不等于200
[2023-08-22 15:39:06,511] logger_util.py->write_log line:61 [INFO] 接口请求失败！
[2023-08-22 15:39:06,511] logger_util.py->write_log line:61 [INFO] -------------接口请求结束-----------

[2023-08-22 15:39:06,511] logger_util.py->error_log line:65 [INFO] 断言异常：异常信息: Traceback (most recent call last):
  File "E:\Project_python\api_cms\common\requests_util.py", line 347, in validate_result
    error_log("断言失败:"+assert_key+"不等于"+str(assert_value))
  File "E:\Project_python\api_cms\common\logger_util.py", line 66, in error_log
    raise Exception(log_message)
Exception: 断言失败:status_code不等于200

[2023-08-22 15:39:06,511] logger_util.py->error_log line:65 [INFO] 分析YAML文件异常：异常信息: Traceback (most recent call last):
  File "E:\Project_python\api_cms\common\requests_util.py", line 347, in validate_result
    error_log("断言失败:"+assert_key+"不等于"+str(assert_value))
  File "E:\Project_python\api_cms\common\logger_util.py", line 66, in error_log
    raise Exception(log_message)
Exception: 断言失败:status_code不等于200

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\Project_python\api_cms\common\requests_util.py", line 249, in analysis_yaml
    self.validate_result(yq_result, return_text, status_code)
  File "E:\Project_python\api_cms\common\requests_util.py", line 401, in validate_result
    error_log("断言异常：异常信息: %s" % str(traceback.format_exc()))
  File "E:\Project_python\api_cms\common\logger_util.py", line 66, in error_log
    raise Exception(log_message)
Exception: 断言异常：异常信息: Traceback (most recent call last):
  File "E:\Project_python\api_cms\common\requests_util.py", line 347, in validate_result
    error_log("断言失败:"+assert_key+"不等于"+str(assert_value))
  File "E:\Project_python\api_cms\common\logger_util.py", line 66, in error_log
    raise Exception(log_message)
Exception: 断言失败:status_code不等于200


[2023-08-22 15:39:06,537] logger_util.py->write_log line:61 [INFO] 
-------------接口请求开始-----------
[2023-08-22 15:39:06,538] logger_util.py->write_log line:61 [INFO] 接口名称：modbus协议下发-离散二进制变量
[2023-08-22 15:39:06,538] logger_util.py->write_log line:61 [INFO] 接口方式：post
[2023-08-22 15:39:06,538] logger_util.py->write_log line:61 [INFO] 接口路径：http://127.0.0.1:6700/v1/cms/io/write
[2023-08-22 15:39:06,538] logger_util.py->write_log line:61 [INFO] 请求头：{'Content-Type': 'application/json'}
[2023-08-22 15:39:06,538] logger_util.py->write_log line:61 [INFO] 请求参数：{'tagDatas': {'MOD_Q1': '0'}}
[2023-08-22 15:39:06,538] logger_util.py->write_log line:61 [INFO] 文件上传：None
[2023-08-22 15:39:08,563] logger_util.py->error_log line:65 [INFO] 断言失败:status_code不等于200
[2023-08-22 15:39:08,564] logger_util.py->write_log line:61 [INFO] 接口请求失败！
[2023-08-22 15:39:08,564] logger_util.py->write_log line:61 [INFO] -------------接口请求结束-----------

[2023-08-22 15:39:08,564] logger_util.py->error_log line:65 [INFO] 断言异常：异常信息: Traceback (most recent call last):
  File "E:\Project_python\api_cms\common\requests_util.py", line 347, in validate_result
    error_log("断言失败:"+assert_key+"不等于"+str(assert_value))
  File "E:\Project_python\api_cms\common\logger_util.py", line 66, in error_log
    raise Exception(log_message)
Exception: 断言失败:status_code不等于200

[2023-08-22 15:39:08,564] logger_util.py->error_log line:65 [INFO] 分析YAML文件异常：异常信息: Traceback (most recent call last):
  File "E:\Project_python\api_cms\common\requests_util.py", line 347, in validate_result
    error_log("断言失败:"+assert_key+"不等于"+str(assert_value))
  File "E:\Project_python\api_cms\common\logger_util.py", line 66, in error_log
    raise Exception(log_message)
Exception: 断言失败:status_code不等于200

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\Project_python\api_cms\common\requests_util.py", line 249, in analysis_yaml
    self.validate_result(yq_result, return_text, status_code)
  File "E:\Project_python\api_cms\common\requests_util.py", line 401, in validate_result
    error_log("断言异常：异常信息: %s" % str(traceback.format_exc()))
  File "E:\Project_python\api_cms\common\logger_util.py", line 66, in error_log
    raise Exception(log_message)
Exception: 断言异常：异常信息: Traceback (most recent call last):
  File "E:\Project_python\api_cms\common\requests_util.py", line 347, in validate_result
    error_log("断言失败:"+assert_key+"不等于"+str(assert_value))
  File "E:\Project_python\api_cms\common\logger_util.py", line 66, in error_log
    raise Exception(log_message)
Exception: 断言失败:status_code不等于200


[2023-08-22 15:39:08,589] logger_util.py->write_log line:61 [INFO] 
-------------接口请求开始-----------
[2023-08-22 15:39:08,590] logger_util.py->write_log line:61 [INFO] 接口名称：modbus协议读取-保存寄存器有符号8位整型
[2023-08-22 15:39:08,590] logger_util.py->write_log line:61 [INFO] 接口方式：post
[2023-08-22 15:39:08,590] logger_util.py->write_log line:61 [INFO] 接口路径：http://127.0.0.1:6700/v1/cms/io/read
[2023-08-22 15:39:08,590] logger_util.py->write_log line:61 [INFO] 请求头：{'Content-Type': 'application/json'}
[2023-08-22 15:39:08,590] logger_util.py->write_log line:61 [INFO] 请求参数：{'tagNames': ['MOD_SINT1']}
[2023-08-22 15:39:08,590] logger_util.py->write_log line:61 [INFO] 文件上传：None
[2023-08-22 15:39:10,617] logger_util.py->error_log line:65 [INFO] 断言失败:status_code不等于200
[2023-08-22 15:39:10,618] logger_util.py->write_log line:61 [INFO] 接口请求失败！
[2023-08-22 15:39:10,618] logger_util.py->write_log line:61 [INFO] -------------接口请求结束-----------

[2023-08-22 15:39:10,618] logger_util.py->error_log line:65 [INFO] 断言异常：异常信息: Traceback (most recent call last):
  File "E:\Project_python\api_cms\common\requests_util.py", line 347, in validate_result
    error_log("断言失败:"+assert_key+"不等于"+str(assert_value))
  File "E:\Project_python\api_cms\common\logger_util.py", line 66, in error_log
    raise Exception(log_message)
Exception: 断言失败:status_code不等于200

[2023-08-22 15:39:10,618] logger_util.py->error_log line:65 [INFO] 分析YAML文件异常：异常信息: Traceback (most recent call last):
  File "E:\Project_python\api_cms\common\requests_util.py", line 347, in validate_result
    error_log("断言失败:"+assert_key+"不等于"+str(assert_value))
  File "E:\Project_python\api_cms\common\logger_util.py", line 66, in error_log
    raise Exception(log_message)
Exception: 断言失败:status_code不等于200

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\Project_python\api_cms\common\requests_util.py", line 249, in analysis_yaml
    self.validate_result(yq_result, return_text, status_code)
  File "E:\Project_python\api_cms\common\requests_util.py", line 401, in validate_result
    error_log("断言异常：异常信息: %s" % str(traceback.format_exc()))
  File "E:\Project_python\api_cms\common\logger_util.py", line 66, in error_log
    raise Exception(log_message)
Exception: 断言异常：异常信息: Traceback (most recent call last):
  File "E:\Project_python\api_cms\common\requests_util.py", line 347, in validate_result
    error_log("断言失败:"+assert_key+"不等于"+str(assert_value))
  File "E:\Project_python\api_cms\common\logger_util.py", line 66, in error_log
    raise Exception(log_message)
Exception: 断言失败:status_code不等于200


[2023-08-22 15:39:10,644] logger_util.py->write_log line:61 [INFO] 
-------------接口请求开始-----------
[2023-08-22 15:39:10,644] logger_util.py->write_log line:61 [INFO] 接口名称：modbus协议读取-保存寄存器有符号16位整型
[2023-08-22 15:39:10,644] logger_util.py->write_log line:61 [INFO] 接口方式：post
[2023-08-22 15:39:10,644] logger_util.py->write_log line:61 [INFO] 接口路径：http://127.0.0.1:6700/v1/cms/io/read
[2023-08-22 15:39:10,644] logger_util.py->write_log line:61 [INFO] 请求头：{'Content-Type': 'application/json'}
[2023-08-22 15:39:10,644] logger_util.py->write_log line:61 [INFO] 请求参数：{'tagNames': ['MOD_INT1']}
[2023-08-22 15:39:10,644] logger_util.py->write_log line:61 [INFO] 文件上传：None
[2023-08-22 15:39:12,669] logger_util.py->error_log line:65 [INFO] 断言失败:status_code不等于200
[2023-08-22 15:39:12,670] logger_util.py->write_log line:61 [INFO] 接口请求失败！
[2023-08-22 15:39:12,670] logger_util.py->write_log line:61 [INFO] -------------接口请求结束-----------

[2023-08-22 15:39:12,670] logger_util.py->error_log line:65 [INFO] 断言异常：异常信息: Traceback (most recent call last):
  File "E:\Project_python\api_cms\common\requests_util.py", line 347, in validate_result
    error_log("断言失败:"+assert_key+"不等于"+str(assert_value))
  File "E:\Project_python\api_cms\common\logger_util.py", line 66, in error_log
    raise Exception(log_message)
Exception: 断言失败:status_code不等于200

[2023-08-22 15:39:12,670] logger_util.py->error_log line:65 [INFO] 分析YAML文件异常：异常信息: Traceback (most recent call last):
  File "E:\Project_python\api_cms\common\requests_util.py", line 347, in validate_result
    error_log("断言失败:"+assert_key+"不等于"+str(assert_value))
  File "E:\Project_python\api_cms\common\logger_util.py", line 66, in error_log
    raise Exception(log_message)
Exception: 断言失败:status_code不等于200

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\Project_python\api_cms\common\requests_util.py", line 249, in analysis_yaml
    self.validate_result(yq_result, return_text, status_code)
  File "E:\Project_python\api_cms\common\requests_util.py", line 401, in validate_result
    error_log("断言异常：异常信息: %s" % str(traceback.format_exc()))
  File "E:\Project_python\api_cms\common\logger_util.py", line 66, in error_log
    raise Exception(log_message)
Exception: 断言异常：异常信息: Traceback (most recent call last):
  File "E:\Project_python\api_cms\common\requests_util.py", line 347, in validate_result
    error_log("断言失败:"+assert_key+"不等于"+str(assert_value))
  File "E:\Project_python\api_cms\common\logger_util.py", line 66, in error_log
    raise Exception(log_message)
Exception: 断言失败:status_code不等于200


[2023-08-22 15:39:12,696] logger_util.py->write_log line:61 [INFO] 
-------------接口请求开始-----------
[2023-08-22 15:39:12,696] logger_util.py->write_log line:61 [INFO] 接口名称：modbus协议读取-保存寄存器有符号32位整型
[2023-08-22 15:39:12,697] logger_util.py->write_log line:61 [INFO] 接口方式：post
[2023-08-22 15:39:12,697] logger_util.py->write_log line:61 [INFO] 接口路径：http://127.0.0.1:6700/v1/cms/io/read
[2023-08-22 15:39:12,697] logger_util.py->write_log line:61 [INFO] 请求头：{'Content-Type': 'application/json'}
[2023-08-22 15:39:12,697] logger_util.py->write_log line:61 [INFO] 请求参数：{'tagNames': ['MOD_DINT1']}
[2023-08-22 15:39:12,697] logger_util.py->write_log line:61 [INFO] 文件上传：None
[2023-08-22 15:39:14,738] logger_util.py->error_log line:65 [INFO] 断言失败:status_code不等于200
[2023-08-22 15:39:14,738] logger_util.py->write_log line:61 [INFO] 接口请求失败！
[2023-08-22 15:39:14,738] logger_util.py->write_log line:61 [INFO] -------------接口请求结束-----------

[2023-08-22 15:39:14,738] logger_util.py->error_log line:65 [INFO] 断言异常：异常信息: Traceback (most recent call last):
  File "E:\Project_python\api_cms\common\requests_util.py", line 347, in validate_result
    error_log("断言失败:"+assert_key+"不等于"+str(assert_value))
  File "E:\Project_python\api_cms\common\logger_util.py", line 66, in error_log
    raise Exception(log_message)
Exception: 断言失败:status_code不等于200

[2023-08-22 15:39:14,738] logger_util.py->error_log line:65 [INFO] 分析YAML文件异常：异常信息: Traceback (most recent call last):
  File "E:\Project_python\api_cms\common\requests_util.py", line 347, in validate_result
    error_log("断言失败:"+assert_key+"不等于"+str(assert_value))
  File "E:\Project_python\api_cms\common\logger_util.py", line 66, in error_log
    raise Exception(log_message)
Exception: 断言失败:status_code不等于200

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\Project_python\api_cms\common\requests_util.py", line 249, in analysis_yaml
    self.validate_result(yq_result, return_text, status_code)
  File "E:\Project_python\api_cms\common\requests_util.py", line 401, in validate_result
    error_log("断言异常：异常信息: %s" % str(traceback.format_exc()))
  File "E:\Project_python\api_cms\common\logger_util.py", line 66, in error_log
    raise Exception(log_message)
Exception: 断言异常：异常信息: Traceback (most recent call last):
  File "E:\Project_python\api_cms\common\requests_util.py", line 347, in validate_result
    error_log("断言失败:"+assert_key+"不等于"+str(assert_value))
  File "E:\Project_python\api_cms\common\logger_util.py", line 66, in error_log
    raise Exception(log_message)
Exception: 断言失败:status_code不等于200


[2023-08-22 15:39:14,763] logger_util.py->write_log line:61 [INFO] 
-------------接口请求开始-----------
[2023-08-22 15:39:14,764] logger_util.py->write_log line:61 [INFO] 接口名称：modbus协议读取-保存寄存器无符号8位整型
[2023-08-22 15:39:14,764] logger_util.py->write_log line:61 [INFO] 接口方式：post
[2023-08-22 15:39:14,764] logger_util.py->write_log line:61 [INFO] 接口路径：http://127.0.0.1:6700/v1/cms/io/read
[2023-08-22 15:39:14,764] logger_util.py->write_log line:61 [INFO] 请求头：{'Content-Type': 'application/json'}
[2023-08-22 15:39:14,764] logger_util.py->write_log line:61 [INFO] 请求参数：{'tagNames': ['MOD_USINT1']}
[2023-08-22 15:39:14,764] logger_util.py->write_log line:61 [INFO] 文件上传：None
[2023-08-22 15:39:16,789] logger_util.py->error_log line:65 [INFO] 断言失败:status_code不等于200
[2023-08-22 15:39:16,790] logger_util.py->write_log line:61 [INFO] 接口请求失败！
[2023-08-22 15:39:16,790] logger_util.py->write_log line:61 [INFO] -------------接口请求结束-----------

[2023-08-22 15:39:16,790] logger_util.py->error_log line:65 [INFO] 断言异常：异常信息: Traceback (most recent call last):
  File "E:\Project_python\api_cms\common\requests_util.py", line 347, in validate_result
    error_log("断言失败:"+assert_key+"不等于"+str(assert_value))
  File "E:\Project_python\api_cms\common\logger_util.py", line 66, in error_log
    raise Exception(log_message)
Exception: 断言失败:status_code不等于200

[2023-08-22 15:39:16,790] logger_util.py->error_log line:65 [INFO] 分析YAML文件异常：异常信息: Traceback (most recent call last):
  File "E:\Project_python\api_cms\common\requests_util.py", line 347, in validate_result
    error_log("断言失败:"+assert_key+"不等于"+str(assert_value))
  File "E:\Project_python\api_cms\common\logger_util.py", line 66, in error_log
    raise Exception(log_message)
Exception: 断言失败:status_code不等于200

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\Project_python\api_cms\common\requests_util.py", line 249, in analysis_yaml
    self.validate_result(yq_result, return_text, status_code)
  File "E:\Project_python\api_cms\common\requests_util.py", line 401, in validate_result
    error_log("断言异常：异常信息: %s" % str(traceback.format_exc()))
  File "E:\Project_python\api_cms\common\logger_util.py", line 66, in error_log
    raise Exception(log_message)
Exception: 断言异常：异常信息: Traceback (most recent call last):
  File "E:\Project_python\api_cms\common\requests_util.py", line 347, in validate_result
    error_log("断言失败:"+assert_key+"不等于"+str(assert_value))
  File "E:\Project_python\api_cms\common\logger_util.py", line 66, in error_log
    raise Exception(log_message)
Exception: 断言失败:status_code不等于200


[2023-08-22 15:39:16,815] logger_util.py->write_log line:61 [INFO] 
-------------接口请求开始-----------
[2023-08-22 15:39:16,815] logger_util.py->write_log line:61 [INFO] 接口名称：modbus协议读取-保存寄存器无符号16位整型
[2023-08-22 15:39:16,815] logger_util.py->write_log line:61 [INFO] 接口方式：post
[2023-08-22 15:39:16,815] logger_util.py->write_log line:61 [INFO] 接口路径：http://127.0.0.1:6700/v1/cms/io/read
[2023-08-22 15:39:16,815] logger_util.py->write_log line:61 [INFO] 请求头：{'Content-Type': 'application/json'}
[2023-08-22 15:39:16,816] logger_util.py->write_log line:61 [INFO] 请求参数：{'tagNames': ['MOD_UINT1']}
[2023-08-22 15:39:16,816] logger_util.py->write_log line:61 [INFO] 文件上传：None
[2023-08-22 15:39:18,839] logger_util.py->error_log line:65 [INFO] 断言失败:status_code不等于200
[2023-08-22 15:39:18,839] logger_util.py->write_log line:61 [INFO] 接口请求失败！
[2023-08-22 15:39:18,839] logger_util.py->write_log line:61 [INFO] -------------接口请求结束-----------

[2023-08-22 15:39:18,839] logger_util.py->error_log line:65 [INFO] 断言异常：异常信息: Traceback (most recent call last):
  File "E:\Project_python\api_cms\common\requests_util.py", line 347, in validate_result
    error_log("断言失败:"+assert_key+"不等于"+str(assert_value))
  File "E:\Project_python\api_cms\common\logger_util.py", line 66, in error_log
    raise Exception(log_message)
Exception: 断言失败:status_code不等于200

[2023-08-22 15:39:18,839] logger_util.py->error_log line:65 [INFO] 分析YAML文件异常：异常信息: Traceback (most recent call last):
  File "E:\Project_python\api_cms\common\requests_util.py", line 347, in validate_result
    error_log("断言失败:"+assert_key+"不等于"+str(assert_value))
  File "E:\Project_python\api_cms\common\logger_util.py", line 66, in error_log
    raise Exception(log_message)
Exception: 断言失败:status_code不等于200

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\Project_python\api_cms\common\requests_util.py", line 249, in analysis_yaml
    self.validate_result(yq_result, return_text, status_code)
  File "E:\Project_python\api_cms\common\requests_util.py", line 401, in validate_result
    error_log("断言异常：异常信息: %s" % str(traceback.format_exc()))
  File "E:\Project_python\api_cms\common\logger_util.py", line 66, in error_log
    raise Exception(log_message)
Exception: 断言异常：异常信息: Traceback (most recent call last):
  File "E:\Project_python\api_cms\common\requests_util.py", line 347, in validate_result
    error_log("断言失败:"+assert_key+"不等于"+str(assert_value))
  File "E:\Project_python\api_cms\common\logger_util.py", line 66, in error_log
    raise Exception(log_message)
Exception: 断言失败:status_code不等于200


[2023-08-22 15:39:18,865] logger_util.py->write_log line:61 [INFO] 
-------------接口请求开始-----------
[2023-08-22 15:39:18,865] logger_util.py->write_log line:61 [INFO] 接口名称：modbus协议读取-保存寄存器无符号32位整型
[2023-08-22 15:39:18,865] logger_util.py->write_log line:61 [INFO] 接口方式：post
[2023-08-22 15:39:18,865] logger_util.py->write_log line:61 [INFO] 接口路径：http://127.0.0.1:6700/v1/cms/io/read
[2023-08-22 15:39:18,866] logger_util.py->write_log line:61 [INFO] 请求头：{'Content-Type': 'application/json'}
[2023-08-22 15:39:18,866] logger_util.py->write_log line:61 [INFO] 请求参数：{'tagNames': ['MOD_UDINT1']}
[2023-08-22 15:39:18,866] logger_util.py->write_log line:61 [INFO] 文件上传：None
[2023-08-22 15:39:20,888] logger_util.py->error_log line:65 [INFO] 断言失败:status_code不等于200
[2023-08-22 15:39:20,888] logger_util.py->write_log line:61 [INFO] 接口请求失败！
[2023-08-22 15:39:20,888] logger_util.py->write_log line:61 [INFO] -------------接口请求结束-----------

[2023-08-22 15:39:20,888] logger_util.py->error_log line:65 [INFO] 断言异常：异常信息: Traceback (most recent call last):
  File "E:\Project_python\api_cms\common\requests_util.py", line 347, in validate_result
    error_log("断言失败:"+assert_key+"不等于"+str(assert_value))
  File "E:\Project_python\api_cms\common\logger_util.py", line 66, in error_log
    raise Exception(log_message)
Exception: 断言失败:status_code不等于200

[2023-08-22 15:39:20,888] logger_util.py->error_log line:65 [INFO] 分析YAML文件异常：异常信息: Traceback (most recent call last):
  File "E:\Project_python\api_cms\common\requests_util.py", line 347, in validate_result
    error_log("断言失败:"+assert_key+"不等于"+str(assert_value))
  File "E:\Project_python\api_cms\common\logger_util.py", line 66, in error_log
    raise Exception(log_message)
Exception: 断言失败:status_code不等于200

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\Project_python\api_cms\common\requests_util.py", line 249, in analysis_yaml
    self.validate_result(yq_result, return_text, status_code)
  File "E:\Project_python\api_cms\common\requests_util.py", line 401, in validate_result
    error_log("断言异常：异常信息: %s" % str(traceback.format_exc()))
  File "E:\Project_python\api_cms\common\logger_util.py", line 66, in error_log
    raise Exception(log_message)
Exception: 断言异常：异常信息: Traceback (most recent call last):
  File "E:\Project_python\api_cms\common\requests_util.py", line 347, in validate_result
    error_log("断言失败:"+assert_key+"不等于"+str(assert_value))
  File "E:\Project_python\api_cms\common\logger_util.py", line 66, in error_log
    raise Exception(log_message)
Exception: 断言失败:status_code不等于200


[2023-08-22 15:39:20,913] logger_util.py->write_log line:61 [INFO] 
-------------接口请求开始-----------
[2023-08-22 15:39:20,913] logger_util.py->write_log line:61 [INFO] 接口名称：modbus协议读取-保存寄存器F32位浮点数IEEE754
[2023-08-22 15:39:20,913] logger_util.py->write_log line:61 [INFO] 接口方式：post
[2023-08-22 15:39:20,913] logger_util.py->write_log line:61 [INFO] 接口路径：http://127.0.0.1:6700/v1/cms/io/read
[2023-08-22 15:39:20,913] logger_util.py->write_log line:61 [INFO] 请求头：{'Content-Type': 'application/json'}
[2023-08-22 15:39:20,913] logger_util.py->write_log line:61 [INFO] 请求参数：{'tagNames': ['MOD_REAL1']}
[2023-08-22 15:39:20,914] logger_util.py->write_log line:61 [INFO] 文件上传：None
[2023-08-22 15:39:23,400] logger_util.py->error_log line:65 [INFO] 断言失败:status_code不等于200
[2023-08-22 15:39:23,400] logger_util.py->write_log line:61 [INFO] 接口请求失败！
[2023-08-22 15:39:23,400] logger_util.py->write_log line:61 [INFO] -------------接口请求结束-----------

[2023-08-22 15:39:23,400] logger_util.py->error_log line:65 [INFO] 断言异常：异常信息: Traceback (most recent call last):
  File "E:\Project_python\api_cms\common\requests_util.py", line 347, in validate_result
    error_log("断言失败:"+assert_key+"不等于"+str(assert_value))
  File "E:\Project_python\api_cms\common\logger_util.py", line 66, in error_log
    raise Exception(log_message)
Exception: 断言失败:status_code不等于200

[2023-08-22 15:39:23,400] logger_util.py->error_log line:65 [INFO] 分析YAML文件异常：异常信息: Traceback (most recent call last):
  File "E:\Project_python\api_cms\common\requests_util.py", line 347, in validate_result
    error_log("断言失败:"+assert_key+"不等于"+str(assert_value))
  File "E:\Project_python\api_cms\common\logger_util.py", line 66, in error_log
    raise Exception(log_message)
Exception: 断言失败:status_code不等于200

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\Project_python\api_cms\common\requests_util.py", line 249, in analysis_yaml
    self.validate_result(yq_result, return_text, status_code)
  File "E:\Project_python\api_cms\common\requests_util.py", line 401, in validate_result
    error_log("断言异常：异常信息: %s" % str(traceback.format_exc()))
  File "E:\Project_python\api_cms\common\logger_util.py", line 66, in error_log
    raise Exception(log_message)
Exception: 断言异常：异常信息: Traceback (most recent call last):
  File "E:\Project_python\api_cms\common\requests_util.py", line 347, in validate_result
    error_log("断言失败:"+assert_key+"不等于"+str(assert_value))
  File "E:\Project_python\api_cms\common\logger_util.py", line 66, in error_log
    raise Exception(log_message)
Exception: 断言失败:status_code不等于200


[2023-08-22 15:39:23,450] logger_util.py->write_log line:61 [INFO] 
-------------接口请求开始-----------
[2023-08-22 15:39:23,451] logger_util.py->write_log line:61 [INFO] 接口名称：modbus协议读取-保存寄存器二进制变量1
[2023-08-22 15:39:23,451] logger_util.py->write_log line:61 [INFO] 接口方式：post
[2023-08-22 15:39:23,451] logger_util.py->write_log line:61 [INFO] 接口路径：http://127.0.0.1:6700/v1/cms/io/read
[2023-08-22 15:39:23,451] logger_util.py->write_log line:61 [INFO] 请求头：{'Content-Type': 'application/json'}
[2023-08-22 15:39:23,451] logger_util.py->write_log line:61 [INFO] 请求参数：{'tagNames': ['MOD_BOOL1']}
[2023-08-22 15:39:23,451] logger_util.py->write_log line:61 [INFO] 文件上传：None
[2023-08-22 15:39:25,907] logger_util.py->error_log line:65 [INFO] 断言失败:status_code不等于200
[2023-08-22 15:39:25,908] logger_util.py->write_log line:61 [INFO] 接口请求失败！
[2023-08-22 15:39:25,908] logger_util.py->write_log line:61 [INFO] -------------接口请求结束-----------

[2023-08-22 15:39:25,908] logger_util.py->error_log line:65 [INFO] 断言异常：异常信息: Traceback (most recent call last):
  File "E:\Project_python\api_cms\common\requests_util.py", line 347, in validate_result
    error_log("断言失败:"+assert_key+"不等于"+str(assert_value))
  File "E:\Project_python\api_cms\common\logger_util.py", line 66, in error_log
    raise Exception(log_message)
Exception: 断言失败:status_code不等于200

[2023-08-22 15:39:25,908] logger_util.py->error_log line:65 [INFO] 分析YAML文件异常：异常信息: Traceback (most recent call last):
  File "E:\Project_python\api_cms\common\requests_util.py", line 347, in validate_result
    error_log("断言失败:"+assert_key+"不等于"+str(assert_value))
  File "E:\Project_python\api_cms\common\logger_util.py", line 66, in error_log
    raise Exception(log_message)
Exception: 断言失败:status_code不等于200

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\Project_python\api_cms\common\requests_util.py", line 249, in analysis_yaml
    self.validate_result(yq_result, return_text, status_code)
  File "E:\Project_python\api_cms\common\requests_util.py", line 401, in validate_result
    error_log("断言异常：异常信息: %s" % str(traceback.format_exc()))
  File "E:\Project_python\api_cms\common\logger_util.py", line 66, in error_log
    raise Exception(log_message)
Exception: 断言异常：异常信息: Traceback (most recent call last):
  File "E:\Project_python\api_cms\common\requests_util.py", line 347, in validate_result
    error_log("断言失败:"+assert_key+"不等于"+str(assert_value))
  File "E:\Project_python\api_cms\common\logger_util.py", line 66, in error_log
    raise Exception(log_message)
Exception: 断言失败:status_code不等于200


[2023-08-22 15:39:25,934] logger_util.py->write_log line:61 [INFO] 
-------------接口请求开始-----------
[2023-08-22 15:39:25,934] logger_util.py->write_log line:61 [INFO] 接口名称：modbus协议读取-保存寄存器二进制变量2
[2023-08-22 15:39:25,934] logger_util.py->write_log line:61 [INFO] 接口方式：post
[2023-08-22 15:39:25,934] logger_util.py->write_log line:61 [INFO] 接口路径：http://127.0.0.1:6700/v1/cms/io/read
[2023-08-22 15:39:25,934] logger_util.py->write_log line:61 [INFO] 请求头：{'Content-Type': 'application/json'}
[2023-08-22 15:39:25,934] logger_util.py->write_log line:61 [INFO] 请求参数：{'tagNames': ['MOD_BOOL2']}
[2023-08-22 15:39:25,934] logger_util.py->write_log line:61 [INFO] 文件上传：None
[2023-08-22 15:39:27,954] logger_util.py->error_log line:65 [INFO] 断言失败:status_code不等于200
[2023-08-22 15:39:27,955] logger_util.py->write_log line:61 [INFO] 接口请求失败！
[2023-08-22 15:39:27,955] logger_util.py->write_log line:61 [INFO] -------------接口请求结束-----------

[2023-08-22 15:39:27,955] logger_util.py->error_log line:65 [INFO] 断言异常：异常信息: Traceback (most recent call last):
  File "E:\Project_python\api_cms\common\requests_util.py", line 347, in validate_result
    error_log("断言失败:"+assert_key+"不等于"+str(assert_value))
  File "E:\Project_python\api_cms\common\logger_util.py", line 66, in error_log
    raise Exception(log_message)
Exception: 断言失败:status_code不等于200

[2023-08-22 15:39:27,955] logger_util.py->error_log line:65 [INFO] 分析YAML文件异常：异常信息: Traceback (most recent call last):
  File "E:\Project_python\api_cms\common\requests_util.py", line 347, in validate_result
    error_log("断言失败:"+assert_key+"不等于"+str(assert_value))
  File "E:\Project_python\api_cms\common\logger_util.py", line 66, in error_log
    raise Exception(log_message)
Exception: 断言失败:status_code不等于200

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\Project_python\api_cms\common\requests_util.py", line 249, in analysis_yaml
    self.validate_result(yq_result, return_text, status_code)
  File "E:\Project_python\api_cms\common\requests_util.py", line 401, in validate_result
    error_log("断言异常：异常信息: %s" % str(traceback.format_exc()))
  File "E:\Project_python\api_cms\common\logger_util.py", line 66, in error_log
    raise Exception(log_message)
Exception: 断言异常：异常信息: Traceback (most recent call last):
  File "E:\Project_python\api_cms\common\requests_util.py", line 347, in validate_result
    error_log("断言失败:"+assert_key+"不等于"+str(assert_value))
  File "E:\Project_python\api_cms\common\logger_util.py", line 66, in error_log
    raise Exception(log_message)
Exception: 断言失败:status_code不等于200


[2023-08-22 15:39:27,992] logger_util.py->write_log line:61 [INFO] 
-------------接口请求开始-----------
[2023-08-22 15:39:27,992] logger_util.py->write_log line:61 [INFO] 接口名称：modbus协议读取-保存寄存器字符串
[2023-08-22 15:39:27,992] logger_util.py->write_log line:61 [INFO] 接口方式：post
[2023-08-22 15:39:27,992] logger_util.py->write_log line:61 [INFO] 接口路径：http://127.0.0.1:6700/v1/cms/io/read
[2023-08-22 15:39:27,992] logger_util.py->write_log line:61 [INFO] 请求头：{'Content-Type': 'application/json'}
[2023-08-22 15:39:27,992] logger_util.py->write_log line:61 [INFO] 请求参数：{'tagNames': ['MOD_STRING1']}
[2023-08-22 15:39:27,992] logger_util.py->write_log line:61 [INFO] 文件上传：None
[2023-08-22 15:39:30,020] logger_util.py->error_log line:65 [INFO] 断言失败:status_code不等于200
[2023-08-22 15:39:30,021] logger_util.py->write_log line:61 [INFO] 接口请求失败！
[2023-08-22 15:39:30,021] logger_util.py->write_log line:61 [INFO] -------------接口请求结束-----------

[2023-08-22 15:39:30,021] logger_util.py->error_log line:65 [INFO] 断言异常：异常信息: Traceback (most recent call last):
  File "E:\Project_python\api_cms\common\requests_util.py", line 347, in validate_result
    error_log("断言失败:"+assert_key+"不等于"+str(assert_value))
  File "E:\Project_python\api_cms\common\logger_util.py", line 66, in error_log
    raise Exception(log_message)
Exception: 断言失败:status_code不等于200

[2023-08-22 15:39:30,021] logger_util.py->error_log line:65 [INFO] 分析YAML文件异常：异常信息: Traceback (most recent call last):
  File "E:\Project_python\api_cms\common\requests_util.py", line 347, in validate_result
    error_log("断言失败:"+assert_key+"不等于"+str(assert_value))
  File "E:\Project_python\api_cms\common\logger_util.py", line 66, in error_log
    raise Exception(log_message)
Exception: 断言失败:status_code不等于200

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\Project_python\api_cms\common\requests_util.py", line 249, in analysis_yaml
    self.validate_result(yq_result, return_text, status_code)
  File "E:\Project_python\api_cms\common\requests_util.py", line 401, in validate_result
    error_log("断言异常：异常信息: %s" % str(traceback.format_exc()))
  File "E:\Project_python\api_cms\common\logger_util.py", line 66, in error_log
    raise Exception(log_message)
Exception: 断言异常：异常信息: Traceback (most recent call last):
  File "E:\Project_python\api_cms\common\requests_util.py", line 347, in validate_result
    error_log("断言失败:"+assert_key+"不等于"+str(assert_value))
  File "E:\Project_python\api_cms\common\logger_util.py", line 66, in error_log
    raise Exception(log_message)
Exception: 断言失败:status_code不等于200


[2023-08-22 15:39:30,047] logger_util.py->write_log line:61 [INFO] 
-------------接口请求开始-----------
[2023-08-22 15:39:30,047] logger_util.py->write_log line:61 [INFO] 接口名称：modbus协议读取-离散二进制变量
[2023-08-22 15:39:30,047] logger_util.py->write_log line:61 [INFO] 接口方式：post
[2023-08-22 15:39:30,047] logger_util.py->write_log line:61 [INFO] 接口路径：http://127.0.0.1:6700/v1/cms/io/read
[2023-08-22 15:39:30,047] logger_util.py->write_log line:61 [INFO] 请求头：{'Content-Type': 'application/json'}
[2023-08-22 15:39:30,047] logger_util.py->write_log line:61 [INFO] 请求参数：{'tagNames': ['MOD_Q0']}
[2023-08-22 15:39:30,047] logger_util.py->write_log line:61 [INFO] 文件上传：None
[2023-08-22 15:39:32,071] logger_util.py->error_log line:65 [INFO] 断言失败:status_code不等于200
[2023-08-22 15:39:32,072] logger_util.py->write_log line:61 [INFO] 接口请求失败！
[2023-08-22 15:39:32,072] logger_util.py->write_log line:61 [INFO] -------------接口请求结束-----------

[2023-08-22 15:39:32,072] logger_util.py->error_log line:65 [INFO] 断言异常：异常信息: Traceback (most recent call last):
  File "E:\Project_python\api_cms\common\requests_util.py", line 347, in validate_result
    error_log("断言失败:"+assert_key+"不等于"+str(assert_value))
  File "E:\Project_python\api_cms\common\logger_util.py", line 66, in error_log
    raise Exception(log_message)
Exception: 断言失败:status_code不等于200

[2023-08-22 15:39:32,072] logger_util.py->error_log line:65 [INFO] 分析YAML文件异常：异常信息: Traceback (most recent call last):
  File "E:\Project_python\api_cms\common\requests_util.py", line 347, in validate_result
    error_log("断言失败:"+assert_key+"不等于"+str(assert_value))
  File "E:\Project_python\api_cms\common\logger_util.py", line 66, in error_log
    raise Exception(log_message)
Exception: 断言失败:status_code不等于200

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\Project_python\api_cms\common\requests_util.py", line 249, in analysis_yaml
    self.validate_result(yq_result, return_text, status_code)
  File "E:\Project_python\api_cms\common\requests_util.py", line 401, in validate_result
    error_log("断言异常：异常信息: %s" % str(traceback.format_exc()))
  File "E:\Project_python\api_cms\common\logger_util.py", line 66, in error_log
    raise Exception(log_message)
Exception: 断言异常：异常信息: Traceback (most recent call last):
  File "E:\Project_python\api_cms\common\requests_util.py", line 347, in validate_result
    error_log("断言失败:"+assert_key+"不等于"+str(assert_value))
  File "E:\Project_python\api_cms\common\logger_util.py", line 66, in error_log
    raise Exception(log_message)
Exception: 断言失败:status_code不等于200


[2023-08-22 15:39:32,098] logger_util.py->write_log line:61 [INFO] 
-------------接口请求开始-----------
[2023-08-22 15:39:32,098] logger_util.py->write_log line:61 [INFO] 接口名称：modbus协议读取-离散二进制变量
[2023-08-22 15:39:32,098] logger_util.py->write_log line:61 [INFO] 接口方式：post
[2023-08-22 15:39:32,098] logger_util.py->write_log line:61 [INFO] 接口路径：http://127.0.0.1:6700/v1/cms/io/read
[2023-08-22 15:39:32,098] logger_util.py->write_log line:61 [INFO] 请求头：{'Content-Type': 'application/json'}
[2023-08-22 15:39:32,098] logger_util.py->write_log line:61 [INFO] 请求参数：{'tagNames': ['MOD_Q1']}
[2023-08-22 15:39:32,098] logger_util.py->write_log line:61 [INFO] 文件上传：None
[2023-08-22 15:39:34,126] logger_util.py->error_log line:65 [INFO] 断言失败:status_code不等于200
[2023-08-22 15:39:34,127] logger_util.py->write_log line:61 [INFO] 接口请求失败！
[2023-08-22 15:39:34,127] logger_util.py->write_log line:61 [INFO] -------------接口请求结束-----------

[2023-08-22 15:39:34,127] logger_util.py->error_log line:65 [INFO] 断言异常：异常信息: Traceback (most recent call last):
  File "E:\Project_python\api_cms\common\requests_util.py", line 347, in validate_result
    error_log("断言失败:"+assert_key+"不等于"+str(assert_value))
  File "E:\Project_python\api_cms\common\logger_util.py", line 66, in error_log
    raise Exception(log_message)
Exception: 断言失败:status_code不等于200

[2023-08-22 15:39:34,127] logger_util.py->error_log line:65 [INFO] 分析YAML文件异常：异常信息: Traceback (most recent call last):
  File "E:\Project_python\api_cms\common\requests_util.py", line 347, in validate_result
    error_log("断言失败:"+assert_key+"不等于"+str(assert_value))
  File "E:\Project_python\api_cms\common\logger_util.py", line 66, in error_log
    raise Exception(log_message)
Exception: 断言失败:status_code不等于200

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\Project_python\api_cms\common\requests_util.py", line 249, in analysis_yaml
    self.validate_result(yq_result, return_text, status_code)
  File "E:\Project_python\api_cms\common\requests_util.py", line 401, in validate_result
    error_log("断言异常：异常信息: %s" % str(traceback.format_exc()))
  File "E:\Project_python\api_cms\common\logger_util.py", line 66, in error_log
    raise Exception(log_message)
Exception: 断言异常：异常信息: Traceback (most recent call last):
  File "E:\Project_python\api_cms\common\requests_util.py", line 347, in validate_result
    error_log("断言失败:"+assert_key+"不等于"+str(assert_value))
  File "E:\Project_python\api_cms\common\logger_util.py", line 66, in error_log
    raise Exception(log_message)
Exception: 断言失败:status_code不等于200


