[2023-08-25 14:55:41,071] logger_util.py->write_log line:61 [INFO] 
-------------接口请求开始-----------
[2023-08-25 14:55:41,071] logger_util.py->write_log line:61 [INFO] 接口名称：创建工程
[2023-08-25 14:55:41,071] logger_util.py->write_log line:61 [INFO] 接口方式：post
[2023-08-25 14:55:41,072] logger_util.py->write_log line:61 [INFO] 接口路径：http://127.0.0.1:18000/api/v1/project/node
[2023-08-25 14:55:41,072] logger_util.py->write_log line:61 [INFO] 请求头：{}
[2023-08-25 14:55:41,072] logger_util.py->write_log line:61 [INFO] 请求参数：{'name': '工程6198', 'path': 'C:\\自动化工程', 'type': 1}
[2023-08-25 14:55:41,074] logger_util.py->write_log line:61 [INFO] 文件上传：None
[2023-08-25 14:55:41,401] logger_util.py->write_log line:61 [INFO] 预期结果：[{'equals': {'status_code': 200}}]
[2023-08-25 14:55:41,401] logger_util.py->write_log line:61 [INFO] 实际结果：473
[2023-08-25 14:55:41,401] logger_util.py->write_log line:61 [INFO] 接口请求成功！
[2023-08-25 14:55:41,401] logger_util.py->write_log line:61 [INFO] 
-------------接口请求结束-----------

[2023-08-25 14:55:51,407] logger_util.py->write_log line:61 [INFO] 
-------------接口请求开始-----------
[2023-08-25 14:55:51,408] logger_util.py->write_log line:61 [INFO] 接口名称：启动变量服务
[2023-08-25 14:55:51,408] logger_util.py->write_log line:61 [INFO] 接口方式：post
[2023-08-25 14:55:51,408] logger_util.py->write_log line:61 [INFO] 接口路径：http://127.0.0.1:18000/api/v1/project/service/var/start
[2023-08-25 14:55:51,408] logger_util.py->write_log line:61 [INFO] 请求头：{}
[2023-08-25 14:55:51,408] logger_util.py->write_log line:61 [INFO] 文件上传：None
[2023-08-25 14:55:51,480] logger_util.py->error_log line:65 [INFO] 断言失败:status_code不等于200
[2023-08-25 14:55:51,481] logger_util.py->write_log line:61 [INFO] 实际结果：An exception was thrown while activating CMS.Unit.Variable.VariableQueryService -> CMS.Unit.Variable.Repository.VarTunnelRepository`1[[CMS.ConfigDb.ConfigDbContext, CMS.ConfigDb, Version=2.0.0.0, Culture=neutral, PublicKeyToken=null]] -> CMS.ConfigDb.ConfigDbContext -> λ:Microsoft.EntityFrameworkCore.DbContextOptions`1[[CMS.ConfigDb.ConfigDbContext, CMS.ConfigDb, Version=2.0.0.0, Culture=neutral, PublicKeyToken=null]].
[2023-08-25 14:55:51,482] logger_util.py->write_log line:61 [INFO] 接口请求失败！
[2023-08-25 14:55:51,483] logger_util.py->write_log line:61 [INFO] -------------接口请求结束-----------

[2023-08-25 14:55:51,485] logger_util.py->error_log line:65 [INFO] 断言异常：异常信息: Traceback (most recent call last):
  File "E:\Project_python\api_cms\common\requests_util.py", line 356, in validate_result
    error_log("断言失败:"+assert_key+"不等于"+str(assert_value))
  File "E:\Project_python\api_cms\common\logger_util.py", line 66, in error_log
    raise Exception(log_message)
Exception: 断言失败:status_code不等于200

[2023-08-25 14:55:51,486] logger_util.py->error_log line:65 [INFO] 分析YAML文件异常：异常信息: Traceback (most recent call last):
  File "E:\Project_python\api_cms\common\requests_util.py", line 356, in validate_result
    error_log("断言失败:"+assert_key+"不等于"+str(assert_value))
  File "E:\Project_python\api_cms\common\logger_util.py", line 66, in error_log
    raise Exception(log_message)
Exception: 断言失败:status_code不等于200

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\Project_python\api_cms\common\requests_util.py", line 255, in analysis_yaml
    self.validate_result(yq_result, return_text, status_code)
  File "E:\Project_python\api_cms\common\requests_util.py", line 413, in validate_result
    error_log("断言异常：异常信息: %s" % str(traceback.format_exc()))
  File "E:\Project_python\api_cms\common\logger_util.py", line 66, in error_log
    raise Exception(log_message)
Exception: 断言异常：异常信息: Traceback (most recent call last):
  File "E:\Project_python\api_cms\common\requests_util.py", line 356, in validate_result
    error_log("断言失败:"+assert_key+"不等于"+str(assert_value))
  File "E:\Project_python\api_cms\common\logger_util.py", line 66, in error_log
    raise Exception(log_message)
Exception: 断言失败:status_code不等于200


