[2023-11-28 09:38:06,163] logger_util.py->write_log line:61 [INFO] 
-------------接口请求开始-----------
[2023-11-28 09:38:06,163] logger_util.py->write_log line:61 [INFO] 接口名称：测试连接互联项
[2023-11-28 09:38:06,164] logger_util.py->write_log line:61 [INFO] 接口方式：post
[2023-11-28 09:38:06,164] logger_util.py->write_log line:61 [INFO] 接口路径：http://127.0.0.1:18000/api/v1/connection/test
[2023-11-28 09:38:06,164] logger_util.py->write_log line:61 [INFO] 请求头：{'X-Project': 'd800d1a6d0be4623aaa824c28dc71981'}
[2023-11-28 09:38:06,164] logger_util.py->write_log line:61 [INFO] 请求参数：{'id': None, 'name': 'mysql3288', 'connectionType': 1, 'databaseType': 1, 'authenticationType': None, 'server': '127.0.0.1', 'port': '3306', 'database': 'TestDB', 'databasePath': '', 'userName': 'root', 'password': 'syc123', 'changedPassword': True, 'mqttType': None, 'pushType': None, 'timingPeriod': None, 'changingPeriod': None, 'cloudDeviceId': '', 'originalSecret': ''}
[2023-11-28 09:38:06,165] logger_util.py->write_log line:61 [INFO] 文件上传：None
[2023-11-28 09:38:06,171] logger_util.py->write_log line:61 [INFO] 预期结果：[{'equals': {'status_code': 200}}]
[2023-11-28 09:38:06,171] logger_util.py->write_log line:61 [INFO] 实际结果：测试连接成功
[2023-11-28 09:38:06,171] logger_util.py->write_log line:61 [INFO] 接口请求成功！
[2023-11-28 09:38:06,172] logger_util.py->write_log line:61 [INFO] 
-------------接口请求结束-----------

[2023-11-28 09:38:06,190] logger_util.py->write_log line:61 [INFO] 
-------------接口请求开始-----------
[2023-11-28 09:38:06,190] logger_util.py->write_log line:61 [INFO] 接口名称：测试连接互联项
[2023-11-28 09:38:06,190] logger_util.py->write_log line:61 [INFO] 接口方式：post
[2023-11-28 09:38:06,190] logger_util.py->write_log line:61 [INFO] 接口路径：http://127.0.0.1:18000/api/v1/connection
[2023-11-28 09:38:06,190] logger_util.py->write_log line:61 [INFO] 请求头：{'X-Project': 'd800d1a6d0be4623aaa824c28dc71981'}
[2023-11-28 09:38:06,190] logger_util.py->write_log line:61 [INFO] 请求参数：{'id': None, 'name': 'mysql2021', 'connectionType': 1, 'databaseType': 1, 'authenticationType': None, 'server': '127.0.0.1', 'port': '3306', 'database': 'TestDB', 'databasePath': '', 'userName': 'root', 'password': 'syc123', 'changedPassword': True, 'mqttType': None, 'pushType': None, 'timingPeriod': None, 'changingPeriod': None, 'cloudDeviceId': '', 'originalSecret': ''}
[2023-11-28 09:38:06,190] logger_util.py->write_log line:61 [INFO] 文件上传：None
[2023-11-28 09:38:06,215] logger_util.py->write_log line:61 [INFO] 预期结果：[{'equals': {'status_code': 200}}]
[2023-11-28 09:38:06,215] logger_util.py->write_log line:61 [INFO] 实际结果：{'data': {'id': 34, 'name': 'mysql2021', 'connectionType': 1, 'databaseType': 1, 'authenticationType': 0, 'server': '127.0.0.1', 'port': 3306, 'database': 'TestDB', 'databasePath': '', 'userName': 'root'}, 'message': ''}
[2023-11-28 09:38:06,215] logger_util.py->write_log line:61 [INFO] 接口请求成功！
[2023-11-28 09:38:06,215] logger_util.py->write_log line:61 [INFO] 
-------------接口请求结束-----------

[2023-11-28 09:38:06,225] logger_util.py->write_log line:61 [INFO] 
-------------接口请求开始-----------
[2023-11-28 09:38:06,225] logger_util.py->write_log line:61 [INFO] 接口名称：关闭互联项
[2023-11-28 09:38:06,225] logger_util.py->write_log line:61 [INFO] 接口方式：put
[2023-11-28 09:38:06,225] logger_util.py->write_log line:61 [INFO] 接口路径：http://127.0.0.1:18000/api/v1/connection/switch/1/34/off
[2023-11-28 09:38:06,225] logger_util.py->write_log line:61 [INFO] 请求头：{'X-Project': 'd800d1a6d0be4623aaa824c28dc71981'}
[2023-11-28 09:38:06,225] logger_util.py->write_log line:61 [INFO] 文件上传：None
[2023-11-28 09:38:06,235] logger_util.py->write_log line:61 [INFO] 预期结果：[{'equals': {'status_code': 200}}]
[2023-11-28 09:38:06,235] logger_util.py->write_log line:61 [INFO] 实际结果：[{'nodeGuid': '6a4ff54f-7e68-470a-80c8-80b12e2a120c', 'id': 34, 'type': 1, 'name': 'mysql2021', 'status': 0, 'errorMsg': None, 'children': []}]
[2023-11-28 09:38:06,235] logger_util.py->write_log line:61 [INFO] 接口请求成功！
[2023-11-28 09:38:06,235] logger_util.py->write_log line:61 [INFO] 
-------------接口请求结束-----------

[2023-11-28 09:38:06,240] logger_util.py->write_log line:61 [INFO] 
-------------接口请求开始-----------
[2023-11-28 09:38:06,241] logger_util.py->write_log line:61 [INFO] 接口名称：开启互联项
[2023-11-28 09:38:06,241] logger_util.py->write_log line:61 [INFO] 接口方式：put
[2023-11-28 09:38:06,241] logger_util.py->write_log line:61 [INFO] 接口路径：http://127.0.0.1:18000/api/v1/connection/switch/1/34/on
[2023-11-28 09:38:06,241] logger_util.py->write_log line:61 [INFO] 请求头：{'X-Project': 'd800d1a6d0be4623aaa824c28dc71981'}
[2023-11-28 09:38:06,241] logger_util.py->write_log line:61 [INFO] 文件上传：None
[2023-11-28 09:38:06,248] logger_util.py->write_log line:61 [INFO] 预期结果：[{'equals': {'status_code': 200}}]
[2023-11-28 09:38:06,249] logger_util.py->write_log line:61 [INFO] 实际结果：[{'nodeGuid': '5b7211a9-65bf-40d1-8264-4d85f89b1349', 'id': 34, 'type': 1, 'name': 'mysql2021', 'status': 0, 'errorMsg': None, 'children': []}]
[2023-11-28 09:38:06,249] logger_util.py->write_log line:61 [INFO] 接口请求成功！
[2023-11-28 09:38:06,249] logger_util.py->write_log line:61 [INFO] 
-------------接口请求结束-----------

[2023-11-28 09:38:06,255] logger_util.py->write_log line:61 [INFO] 
-------------接口请求开始-----------
[2023-11-28 09:38:06,255] logger_util.py->write_log line:61 [INFO] 接口名称：重命名互联项
[2023-11-28 09:38:06,255] logger_util.py->write_log line:61 [INFO] 接口方式：put
[2023-11-28 09:38:06,255] logger_util.py->write_log line:61 [INFO] 接口路径：http://127.0.0.1:18000/api/v1/connection/rename/1/34/重命名_mysql958
[2023-11-28 09:38:06,256] logger_util.py->write_log line:61 [INFO] 请求头：{'X-Project': 'd800d1a6d0be4623aaa824c28dc71981'}
[2023-11-28 09:38:06,256] logger_util.py->write_log line:61 [INFO] 文件上传：None
[2023-11-28 09:38:06,279] logger_util.py->write_log line:61 [INFO] 预期结果：[{'equals': {'status_code': 200}}]
[2023-11-28 09:38:06,279] logger_util.py->write_log line:61 [INFO] 实际结果：
[2023-11-28 09:38:06,279] logger_util.py->write_log line:61 [INFO] 接口请求成功！
[2023-11-28 09:38:06,279] logger_util.py->write_log line:61 [INFO] 
-------------接口请求结束-----------

[2023-11-28 09:38:06,295] logger_util.py->write_log line:61 [INFO] 
-------------接口请求开始-----------
[2023-11-28 09:38:06,295] logger_util.py->write_log line:61 [INFO] 接口名称：修改互联配置
[2023-11-28 09:38:06,295] logger_util.py->write_log line:61 [INFO] 接口方式：put
[2023-11-28 09:38:06,295] logger_util.py->write_log line:61 [INFO] 接口路径：http://127.0.0.1:18000/api/v1/connection/34/config
[2023-11-28 09:38:06,295] logger_util.py->write_log line:61 [INFO] 请求头：{'X-Project': 'd800d1a6d0be4623aaa824c28dc71981'}
[2023-11-28 09:38:06,295] logger_util.py->write_log line:61 [INFO] 请求参数：{'id': 34, 'name': '改配_mysql130', 'connectionType': 1, 'databaseType': 1, 'authenticationType': 0, 'server': '127.0.0.1', 'port': '3306', 'database': 'TestDB', 'databasePath': '', 'userName': 'root', 'password': 'syc123'}
[2023-11-28 09:38:06,295] logger_util.py->write_log line:61 [INFO] 文件上传：None
[2023-11-28 09:38:06,320] logger_util.py->write_log line:61 [INFO] 预期结果：[{'equals': {'status_code': 200}}]
[2023-11-28 09:38:06,320] logger_util.py->write_log line:61 [INFO] 实际结果：{'data': {'id': 34, 'name': '改配_mysql130', 'connectionType': 1, 'databaseType': 1, 'authenticationType': 0, 'server': '127.0.0.1', 'port': 3306, 'database': 'TestDB', 'databasePath': '', 'userName': 'root'}, 'message': ''}
[2023-11-28 09:38:06,320] logger_util.py->write_log line:61 [INFO] 接口请求成功！
[2023-11-28 09:38:06,320] logger_util.py->write_log line:61 [INFO] 
-------------接口请求结束-----------

[2023-11-28 09:38:06,338] logger_util.py->write_log line:61 [INFO] 
-------------接口请求开始-----------
[2023-11-28 09:38:06,338] logger_util.py->write_log line:61 [INFO] 接口名称：删除互联项
[2023-11-28 09:38:06,338] logger_util.py->write_log line:61 [INFO] 接口方式：delete
[2023-11-28 09:38:06,338] logger_util.py->write_log line:61 [INFO] 接口路径：http://127.0.0.1:18000/api/v1/connection/1/34
[2023-11-28 09:38:06,338] logger_util.py->write_log line:61 [INFO] 请求头：{'X-Project': 'd800d1a6d0be4623aaa824c28dc71981'}
[2023-11-28 09:38:06,338] logger_util.py->write_log line:61 [INFO] 文件上传：None
[2023-11-28 09:38:06,361] logger_util.py->write_log line:61 [INFO] 预期结果：[{'equals': {'status_code': 200}}]
[2023-11-28 09:38:06,361] logger_util.py->write_log line:61 [INFO] 实际结果：
[2023-11-28 09:38:06,361] logger_util.py->write_log line:61 [INFO] 接口请求成功！
[2023-11-28 09:38:06,361] logger_util.py->write_log line:61 [INFO] 
-------------接口请求结束-----------

[2023-11-28 09:38:06,378] logger_util.py->write_log line:61 [INFO] 
-------------接口请求开始-----------
[2023-11-28 09:38:06,378] logger_util.py->write_log line:61 [INFO] 接口名称：测试连接互联项
[2023-11-28 09:38:06,378] logger_util.py->write_log line:61 [INFO] 接口方式：post
[2023-11-28 09:38:06,378] logger_util.py->write_log line:61 [INFO] 接口路径：http://127.0.0.1:18000/api/v1/connection
[2023-11-28 09:38:06,378] logger_util.py->write_log line:61 [INFO] 请求头：{'X-Project': 'd800d1a6d0be4623aaa824c28dc71981'}
[2023-11-28 09:38:06,378] logger_util.py->write_log line:61 [INFO] 请求参数：{'id': None, 'name': 'mysql1158', 'connectionType': 1, 'databaseType': 1, 'authenticationType': None, 'server': '127.0.0.1', 'port': '3306', 'database': 'TestDB', 'databasePath': '', 'userName': 'root', 'password': 'syc123', 'changedPassword': True, 'mqttType': None, 'pushType': None, 'timingPeriod': None, 'changingPeriod': None, 'cloudDeviceId': '', 'originalSecret': ''}
[2023-11-28 09:38:06,378] logger_util.py->write_log line:61 [INFO] 文件上传：None
[2023-11-28 09:38:06,398] logger_util.py->write_log line:61 [INFO] 预期结果：[{'equals': {'status_code': 200}}]
[2023-11-28 09:38:06,399] logger_util.py->write_log line:61 [INFO] 实际结果：{'data': {'id': 35, 'name': 'mysql1158', 'connectionType': 1, 'databaseType': 1, 'authenticationType': 0, 'server': '127.0.0.1', 'port': 3306, 'database': 'TestDB', 'databasePath': '', 'userName': 'root'}, 'message': ''}
[2023-11-28 09:38:06,399] logger_util.py->write_log line:61 [INFO] 接口请求成功！
[2023-11-28 09:38:06,399] logger_util.py->write_log line:61 [INFO] 
-------------接口请求结束-----------

[2023-11-28 09:38:06,406] logger_util.py->write_log line:61 [INFO] 
-------------接口请求开始-----------
[2023-11-28 09:38:06,406] logger_util.py->write_log line:61 [INFO] 接口名称：创建映射表表
[2023-11-28 09:38:06,406] logger_util.py->write_log line:61 [INFO] 接口方式：post
[2023-11-28 09:38:06,406] logger_util.py->write_log line:61 [INFO] 接口路径：http://127.0.0.1:18000/api/v1/connection/25/table
[2023-11-28 09:38:06,406] logger_util.py->write_log line:61 [INFO] 请求头：{'X-Project': 'd800d1a6d0be4623aaa824c28dc71981'}
[2023-11-28 09:38:06,406] logger_util.py->write_log line:61 [INFO] 请求参数：{'isBasic': True, 'databaseTableName': 'student', 'querySql': '', 'name': '插入5978'}
[2023-11-28 09:38:06,406] logger_util.py->write_log line:61 [INFO] 文件上传：None
[2023-11-28 09:38:06,973] logger_util.py->error_log line:65 [INFO] 分析YAML文件异常：异常信息: Traceback (most recent call last):
  File "E:\Project_python\api_cms\common\requests_util.py", line 241, in analysis_yaml
    extract_data = {key: value_data[0]}
TypeError: 'bool' object is not subscriptable

[2023-11-28 09:38:07,093] logger_util.py->error_log line:65 [INFO] 发送请求异常：异常信息: Traceback (most recent call last):
  File "E:\Project_python\api_cms\common\requests_util.py", line 309, in send_request
    self.base_url = self.replace_load(self.base_url) + self.replace_load(url)
  File "E:\Project_python\api_cms\common\requests_util.py", line 140, in replace_load
    new_value = getattr(DubugTalk(), func_name)(*args_value.split(','))
  File "E:\Project_python\api_cms\debug_talk.py", line 26, in get_extract_data
    return read_extract_file(node_name)
  File "E:\Project_python\api_cms\common\yaml_util.py", line 19, in read_extract_file
    return value[one_node]
KeyError: 'maptable_id'

[2023-11-28 09:38:07,094] logger_util.py->error_log line:65 [INFO] 分析YAML文件异常：异常信息: Traceback (most recent call last):
  File "E:\Project_python\api_cms\common\requests_util.py", line 309, in send_request
    self.base_url = self.replace_load(self.base_url) + self.replace_load(url)
  File "E:\Project_python\api_cms\common\requests_util.py", line 140, in replace_load
    new_value = getattr(DubugTalk(), func_name)(*args_value.split(','))
  File "E:\Project_python\api_cms\debug_talk.py", line 26, in get_extract_data
    return read_extract_file(node_name)
  File "E:\Project_python\api_cms\common\yaml_util.py", line 19, in read_extract_file
    return value[one_node]
KeyError: 'maptable_id'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\Project_python\api_cms\common\requests_util.py", line 185, in analysis_yaml
    res = self.send_request(name =name,method=method,
  File "E:\Project_python\api_cms\common\requests_util.py", line 335, in send_request
    error_log("发送请求异常：异常信息: %s" % str(traceback.format_exc()))
  File "E:\Project_python\api_cms\common\logger_util.py", line 66, in error_log
    raise Exception(log_message)
Exception: 发送请求异常：异常信息: Traceback (most recent call last):
  File "E:\Project_python\api_cms\common\requests_util.py", line 309, in send_request
    self.base_url = self.replace_load(self.base_url) + self.replace_load(url)
  File "E:\Project_python\api_cms\common\requests_util.py", line 140, in replace_load
    new_value = getattr(DubugTalk(), func_name)(*args_value.split(','))
  File "E:\Project_python\api_cms\debug_talk.py", line 26, in get_extract_data
    return read_extract_file(node_name)
  File "E:\Project_python\api_cms\common\yaml_util.py", line 19, in read_extract_file
    return value[one_node]
KeyError: 'maptable_id'


[2023-11-28 09:38:07,136] logger_util.py->error_log line:65 [INFO] 发送请求异常：异常信息: Traceback (most recent call last):
  File "E:\Project_python\api_cms\common\requests_util.py", line 309, in send_request
    self.base_url = self.replace_load(self.base_url) + self.replace_load(url)
  File "E:\Project_python\api_cms\common\requests_util.py", line 140, in replace_load
    new_value = getattr(DubugTalk(), func_name)(*args_value.split(','))
  File "E:\Project_python\api_cms\debug_talk.py", line 26, in get_extract_data
    return read_extract_file(node_name)
  File "E:\Project_python\api_cms\common\yaml_util.py", line 19, in read_extract_file
    return value[one_node]
KeyError: 'maptable_id'

[2023-11-28 09:38:07,136] logger_util.py->error_log line:65 [INFO] 分析YAML文件异常：异常信息: Traceback (most recent call last):
  File "E:\Project_python\api_cms\common\requests_util.py", line 309, in send_request
    self.base_url = self.replace_load(self.base_url) + self.replace_load(url)
  File "E:\Project_python\api_cms\common\requests_util.py", line 140, in replace_load
    new_value = getattr(DubugTalk(), func_name)(*args_value.split(','))
  File "E:\Project_python\api_cms\debug_talk.py", line 26, in get_extract_data
    return read_extract_file(node_name)
  File "E:\Project_python\api_cms\common\yaml_util.py", line 19, in read_extract_file
    return value[one_node]
KeyError: 'maptable_id'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\Project_python\api_cms\common\requests_util.py", line 185, in analysis_yaml
    res = self.send_request(name =name,method=method,
  File "E:\Project_python\api_cms\common\requests_util.py", line 335, in send_request
    error_log("发送请求异常：异常信息: %s" % str(traceback.format_exc()))
  File "E:\Project_python\api_cms\common\logger_util.py", line 66, in error_log
    raise Exception(log_message)
Exception: 发送请求异常：异常信息: Traceback (most recent call last):
  File "E:\Project_python\api_cms\common\requests_util.py", line 309, in send_request
    self.base_url = self.replace_load(self.base_url) + self.replace_load(url)
  File "E:\Project_python\api_cms\common\requests_util.py", line 140, in replace_load
    new_value = getattr(DubugTalk(), func_name)(*args_value.split(','))
  File "E:\Project_python\api_cms\debug_talk.py", line 26, in get_extract_data
    return read_extract_file(node_name)
  File "E:\Project_python\api_cms\common\yaml_util.py", line 19, in read_extract_file
    return value[one_node]
KeyError: 'maptable_id'


[2023-11-28 09:38:07,178] logger_util.py->error_log line:65 [INFO] 发送请求异常：异常信息: Traceback (most recent call last):
  File "E:\Project_python\api_cms\common\requests_util.py", line 309, in send_request
    self.base_url = self.replace_load(self.base_url) + self.replace_load(url)
  File "E:\Project_python\api_cms\common\requests_util.py", line 140, in replace_load
    new_value = getattr(DubugTalk(), func_name)(*args_value.split(','))
  File "E:\Project_python\api_cms\debug_talk.py", line 26, in get_extract_data
    return read_extract_file(node_name)
  File "E:\Project_python\api_cms\common\yaml_util.py", line 19, in read_extract_file
    return value[one_node]
KeyError: 'maptable_id'

[2023-11-28 09:38:07,179] logger_util.py->error_log line:65 [INFO] 分析YAML文件异常：异常信息: Traceback (most recent call last):
  File "E:\Project_python\api_cms\common\requests_util.py", line 309, in send_request
    self.base_url = self.replace_load(self.base_url) + self.replace_load(url)
  File "E:\Project_python\api_cms\common\requests_util.py", line 140, in replace_load
    new_value = getattr(DubugTalk(), func_name)(*args_value.split(','))
  File "E:\Project_python\api_cms\debug_talk.py", line 26, in get_extract_data
    return read_extract_file(node_name)
  File "E:\Project_python\api_cms\common\yaml_util.py", line 19, in read_extract_file
    return value[one_node]
KeyError: 'maptable_id'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\Project_python\api_cms\common\requests_util.py", line 185, in analysis_yaml
    res = self.send_request(name =name,method=method,
  File "E:\Project_python\api_cms\common\requests_util.py", line 335, in send_request
    error_log("发送请求异常：异常信息: %s" % str(traceback.format_exc()))
  File "E:\Project_python\api_cms\common\logger_util.py", line 66, in error_log
    raise Exception(log_message)
Exception: 发送请求异常：异常信息: Traceback (most recent call last):
  File "E:\Project_python\api_cms\common\requests_util.py", line 309, in send_request
    self.base_url = self.replace_load(self.base_url) + self.replace_load(url)
  File "E:\Project_python\api_cms\common\requests_util.py", line 140, in replace_load
    new_value = getattr(DubugTalk(), func_name)(*args_value.split(','))
  File "E:\Project_python\api_cms\debug_talk.py", line 26, in get_extract_data
    return read_extract_file(node_name)
  File "E:\Project_python\api_cms\common\yaml_util.py", line 19, in read_extract_file
    return value[one_node]
KeyError: 'maptable_id'


[2023-11-28 09:38:07,223] logger_util.py->error_log line:65 [INFO] 发送请求异常：异常信息: Traceback (most recent call last):
  File "E:\Project_python\api_cms\common\requests_util.py", line 309, in send_request
    self.base_url = self.replace_load(self.base_url) + self.replace_load(url)
  File "E:\Project_python\api_cms\common\requests_util.py", line 140, in replace_load
    new_value = getattr(DubugTalk(), func_name)(*args_value.split(','))
  File "E:\Project_python\api_cms\debug_talk.py", line 26, in get_extract_data
    return read_extract_file(node_name)
  File "E:\Project_python\api_cms\common\yaml_util.py", line 19, in read_extract_file
    return value[one_node]
KeyError: 'maptable_id'

[2023-11-28 09:38:07,223] logger_util.py->error_log line:65 [INFO] 分析YAML文件异常：异常信息: Traceback (most recent call last):
  File "E:\Project_python\api_cms\common\requests_util.py", line 309, in send_request
    self.base_url = self.replace_load(self.base_url) + self.replace_load(url)
  File "E:\Project_python\api_cms\common\requests_util.py", line 140, in replace_load
    new_value = getattr(DubugTalk(), func_name)(*args_value.split(','))
  File "E:\Project_python\api_cms\debug_talk.py", line 26, in get_extract_data
    return read_extract_file(node_name)
  File "E:\Project_python\api_cms\common\yaml_util.py", line 19, in read_extract_file
    return value[one_node]
KeyError: 'maptable_id'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\Project_python\api_cms\common\requests_util.py", line 185, in analysis_yaml
    res = self.send_request(name =name,method=method,
  File "E:\Project_python\api_cms\common\requests_util.py", line 335, in send_request
    error_log("发送请求异常：异常信息: %s" % str(traceback.format_exc()))
  File "E:\Project_python\api_cms\common\logger_util.py", line 66, in error_log
    raise Exception(log_message)
Exception: 发送请求异常：异常信息: Traceback (most recent call last):
  File "E:\Project_python\api_cms\common\requests_util.py", line 309, in send_request
    self.base_url = self.replace_load(self.base_url) + self.replace_load(url)
  File "E:\Project_python\api_cms\common\requests_util.py", line 140, in replace_load
    new_value = getattr(DubugTalk(), func_name)(*args_value.split(','))
  File "E:\Project_python\api_cms\debug_talk.py", line 26, in get_extract_data
    return read_extract_file(node_name)
  File "E:\Project_python\api_cms\common\yaml_util.py", line 19, in read_extract_file
    return value[one_node]
KeyError: 'maptable_id'


