[2023-08-23 10:45:31,956] logger_util.py->error_log line:65 [INFO] 发送请求异常：异常信息: Traceback (most recent call last):
  File "E:\Project_python\api_cms\common\requests_util.py", line 306, in send_request
    kwargs[key] = self.replace_load(value)
  File "E:\Project_python\api_cms\common\requests_util.py", line 152, in replace_load
    data = self.int_load(data)
  File "E:\Project_python\api_cms\common\requests_util.py", line 115, in int_load
    data = self.list_load(data)
  File "E:\Project_python\api_cms\common\requests_util.py", line 54, in list_load
    elif isinstance(dict,value):
TypeError: isinstance() arg 2 must be a type or tuple of types

[2023-08-23 10:45:31,956] logger_util.py->error_log line:65 [INFO] 分析YAML文件异常：异常信息: Traceback (most recent call last):
  File "E:\Project_python\api_cms\common\requests_util.py", line 306, in send_request
    kwargs[key] = self.replace_load(value)
  File "E:\Project_python\api_cms\common\requests_util.py", line 152, in replace_load
    data = self.int_load(data)
  File "E:\Project_python\api_cms\common\requests_util.py", line 115, in int_load
    data = self.list_load(data)
  File "E:\Project_python\api_cms\common\requests_util.py", line 54, in list_load
    elif isinstance(dict,value):
TypeError: isinstance() arg 2 must be a type or tuple of types

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\Project_python\api_cms\common\requests_util.py", line 187, in analysis_yaml
    res = self.send_request(name =name,method=method,
  File "E:\Project_python\api_cms\common\requests_util.py", line 325, in send_request
    error_log("发送请求异常：异常信息: %s" % str(traceback.format_exc()))
  File "E:\Project_python\api_cms\common\logger_util.py", line 66, in error_log
    raise Exception(log_message)
Exception: 发送请求异常：异常信息: Traceback (most recent call last):
  File "E:\Project_python\api_cms\common\requests_util.py", line 306, in send_request
    kwargs[key] = self.replace_load(value)
  File "E:\Project_python\api_cms\common\requests_util.py", line 152, in replace_load
    data = self.int_load(data)
  File "E:\Project_python\api_cms\common\requests_util.py", line 115, in int_load
    data = self.list_load(data)
  File "E:\Project_python\api_cms\common\requests_util.py", line 54, in list_load
    elif isinstance(dict,value):
TypeError: isinstance() arg 2 must be a type or tuple of types


[2023-08-23 10:45:32,069] logger_util.py->error_log line:65 [INFO] 发送请求异常：异常信息: Traceback (most recent call last):
  File "E:\Project_python\api_cms\common\requests_util.py", line 306, in send_request
    kwargs[key] = self.replace_load(value)
  File "E:\Project_python\api_cms\common\requests_util.py", line 152, in replace_load
    data = self.int_load(data)
  File "E:\Project_python\api_cms\common\requests_util.py", line 115, in int_load
    data = self.list_load(data)
  File "E:\Project_python\api_cms\common\requests_util.py", line 54, in list_load
    elif isinstance(dict,value):
TypeError: isinstance() arg 2 must be a type or tuple of types

[2023-08-23 10:45:32,069] logger_util.py->error_log line:65 [INFO] 分析YAML文件异常：异常信息: Traceback (most recent call last):
  File "E:\Project_python\api_cms\common\requests_util.py", line 306, in send_request
    kwargs[key] = self.replace_load(value)
  File "E:\Project_python\api_cms\common\requests_util.py", line 152, in replace_load
    data = self.int_load(data)
  File "E:\Project_python\api_cms\common\requests_util.py", line 115, in int_load
    data = self.list_load(data)
  File "E:\Project_python\api_cms\common\requests_util.py", line 54, in list_load
    elif isinstance(dict,value):
TypeError: isinstance() arg 2 must be a type or tuple of types

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\Project_python\api_cms\common\requests_util.py", line 187, in analysis_yaml
    res = self.send_request(name =name,method=method,
  File "E:\Project_python\api_cms\common\requests_util.py", line 325, in send_request
    error_log("发送请求异常：异常信息: %s" % str(traceback.format_exc()))
  File "E:\Project_python\api_cms\common\logger_util.py", line 66, in error_log
    raise Exception(log_message)
Exception: 发送请求异常：异常信息: Traceback (most recent call last):
  File "E:\Project_python\api_cms\common\requests_util.py", line 306, in send_request
    kwargs[key] = self.replace_load(value)
  File "E:\Project_python\api_cms\common\requests_util.py", line 152, in replace_load
    data = self.int_load(data)
  File "E:\Project_python\api_cms\common\requests_util.py", line 115, in int_load
    data = self.list_load(data)
  File "E:\Project_python\api_cms\common\requests_util.py", line 54, in list_load
    elif isinstance(dict,value):
TypeError: isinstance() arg 2 must be a type or tuple of types


[2023-08-23 10:45:32,103] logger_util.py->error_log line:65 [INFO] 发送请求异常：异常信息: Traceback (most recent call last):
  File "E:\Project_python\api_cms\common\requests_util.py", line 306, in send_request
    kwargs[key] = self.replace_load(value)
  File "E:\Project_python\api_cms\common\requests_util.py", line 152, in replace_load
    data = self.int_load(data)
  File "E:\Project_python\api_cms\common\requests_util.py", line 115, in int_load
    data = self.list_load(data)
  File "E:\Project_python\api_cms\common\requests_util.py", line 54, in list_load
    elif isinstance(dict,value):
TypeError: isinstance() arg 2 must be a type or tuple of types

[2023-08-23 10:45:32,104] logger_util.py->error_log line:65 [INFO] 分析YAML文件异常：异常信息: Traceback (most recent call last):
  File "E:\Project_python\api_cms\common\requests_util.py", line 306, in send_request
    kwargs[key] = self.replace_load(value)
  File "E:\Project_python\api_cms\common\requests_util.py", line 152, in replace_load
    data = self.int_load(data)
  File "E:\Project_python\api_cms\common\requests_util.py", line 115, in int_load
    data = self.list_load(data)
  File "E:\Project_python\api_cms\common\requests_util.py", line 54, in list_load
    elif isinstance(dict,value):
TypeError: isinstance() arg 2 must be a type or tuple of types

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\Project_python\api_cms\common\requests_util.py", line 187, in analysis_yaml
    res = self.send_request(name =name,method=method,
  File "E:\Project_python\api_cms\common\requests_util.py", line 325, in send_request
    error_log("发送请求异常：异常信息: %s" % str(traceback.format_exc()))
  File "E:\Project_python\api_cms\common\logger_util.py", line 66, in error_log
    raise Exception(log_message)
Exception: 发送请求异常：异常信息: Traceback (most recent call last):
  File "E:\Project_python\api_cms\common\requests_util.py", line 306, in send_request
    kwargs[key] = self.replace_load(value)
  File "E:\Project_python\api_cms\common\requests_util.py", line 152, in replace_load
    data = self.int_load(data)
  File "E:\Project_python\api_cms\common\requests_util.py", line 115, in int_load
    data = self.list_load(data)
  File "E:\Project_python\api_cms\common\requests_util.py", line 54, in list_load
    elif isinstance(dict,value):
TypeError: isinstance() arg 2 must be a type or tuple of types


[2023-08-23 10:45:32,137] logger_util.py->error_log line:65 [INFO] 发送请求异常：异常信息: Traceback (most recent call last):
  File "E:\Project_python\api_cms\common\requests_util.py", line 306, in send_request
    kwargs[key] = self.replace_load(value)
  File "E:\Project_python\api_cms\common\requests_util.py", line 152, in replace_load
    data = self.int_load(data)
  File "E:\Project_python\api_cms\common\requests_util.py", line 115, in int_load
    data = self.list_load(data)
  File "E:\Project_python\api_cms\common\requests_util.py", line 54, in list_load
    elif isinstance(dict,value):
TypeError: isinstance() arg 2 must be a type or tuple of types

[2023-08-23 10:45:32,137] logger_util.py->error_log line:65 [INFO] 分析YAML文件异常：异常信息: Traceback (most recent call last):
  File "E:\Project_python\api_cms\common\requests_util.py", line 306, in send_request
    kwargs[key] = self.replace_load(value)
  File "E:\Project_python\api_cms\common\requests_util.py", line 152, in replace_load
    data = self.int_load(data)
  File "E:\Project_python\api_cms\common\requests_util.py", line 115, in int_load
    data = self.list_load(data)
  File "E:\Project_python\api_cms\common\requests_util.py", line 54, in list_load
    elif isinstance(dict,value):
TypeError: isinstance() arg 2 must be a type or tuple of types

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\Project_python\api_cms\common\requests_util.py", line 187, in analysis_yaml
    res = self.send_request(name =name,method=method,
  File "E:\Project_python\api_cms\common\requests_util.py", line 325, in send_request
    error_log("发送请求异常：异常信息: %s" % str(traceback.format_exc()))
  File "E:\Project_python\api_cms\common\logger_util.py", line 66, in error_log
    raise Exception(log_message)
Exception: 发送请求异常：异常信息: Traceback (most recent call last):
  File "E:\Project_python\api_cms\common\requests_util.py", line 306, in send_request
    kwargs[key] = self.replace_load(value)
  File "E:\Project_python\api_cms\common\requests_util.py", line 152, in replace_load
    data = self.int_load(data)
  File "E:\Project_python\api_cms\common\requests_util.py", line 115, in int_load
    data = self.list_load(data)
  File "E:\Project_python\api_cms\common\requests_util.py", line 54, in list_load
    elif isinstance(dict,value):
TypeError: isinstance() arg 2 must be a type or tuple of types


[2023-08-23 10:45:32,170] logger_util.py->error_log line:65 [INFO] 发送请求异常：异常信息: Traceback (most recent call last):
  File "E:\Project_python\api_cms\common\requests_util.py", line 306, in send_request
    kwargs[key] = self.replace_load(value)
  File "E:\Project_python\api_cms\common\requests_util.py", line 152, in replace_load
    data = self.int_load(data)
  File "E:\Project_python\api_cms\common\requests_util.py", line 115, in int_load
    data = self.list_load(data)
  File "E:\Project_python\api_cms\common\requests_util.py", line 54, in list_load
    elif isinstance(dict,value):
TypeError: isinstance() arg 2 must be a type or tuple of types

[2023-08-23 10:45:32,171] logger_util.py->error_log line:65 [INFO] 分析YAML文件异常：异常信息: Traceback (most recent call last):
  File "E:\Project_python\api_cms\common\requests_util.py", line 306, in send_request
    kwargs[key] = self.replace_load(value)
  File "E:\Project_python\api_cms\common\requests_util.py", line 152, in replace_load
    data = self.int_load(data)
  File "E:\Project_python\api_cms\common\requests_util.py", line 115, in int_load
    data = self.list_load(data)
  File "E:\Project_python\api_cms\common\requests_util.py", line 54, in list_load
    elif isinstance(dict,value):
TypeError: isinstance() arg 2 must be a type or tuple of types

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\Project_python\api_cms\common\requests_util.py", line 187, in analysis_yaml
    res = self.send_request(name =name,method=method,
  File "E:\Project_python\api_cms\common\requests_util.py", line 325, in send_request
    error_log("发送请求异常：异常信息: %s" % str(traceback.format_exc()))
  File "E:\Project_python\api_cms\common\logger_util.py", line 66, in error_log
    raise Exception(log_message)
Exception: 发送请求异常：异常信息: Traceback (most recent call last):
  File "E:\Project_python\api_cms\common\requests_util.py", line 306, in send_request
    kwargs[key] = self.replace_load(value)
  File "E:\Project_python\api_cms\common\requests_util.py", line 152, in replace_load
    data = self.int_load(data)
  File "E:\Project_python\api_cms\common\requests_util.py", line 115, in int_load
    data = self.list_load(data)
  File "E:\Project_python\api_cms\common\requests_util.py", line 54, in list_load
    elif isinstance(dict,value):
TypeError: isinstance() arg 2 must be a type or tuple of types


[2023-08-23 10:45:32,204] logger_util.py->error_log line:65 [INFO] 发送请求异常：异常信息: Traceback (most recent call last):
  File "E:\Project_python\api_cms\common\requests_util.py", line 306, in send_request
    kwargs[key] = self.replace_load(value)
  File "E:\Project_python\api_cms\common\requests_util.py", line 152, in replace_load
    data = self.int_load(data)
  File "E:\Project_python\api_cms\common\requests_util.py", line 115, in int_load
    data = self.list_load(data)
  File "E:\Project_python\api_cms\common\requests_util.py", line 54, in list_load
    elif isinstance(dict,value):
TypeError: isinstance() arg 2 must be a type or tuple of types

[2023-08-23 10:45:32,204] logger_util.py->error_log line:65 [INFO] 分析YAML文件异常：异常信息: Traceback (most recent call last):
  File "E:\Project_python\api_cms\common\requests_util.py", line 306, in send_request
    kwargs[key] = self.replace_load(value)
  File "E:\Project_python\api_cms\common\requests_util.py", line 152, in replace_load
    data = self.int_load(data)
  File "E:\Project_python\api_cms\common\requests_util.py", line 115, in int_load
    data = self.list_load(data)
  File "E:\Project_python\api_cms\common\requests_util.py", line 54, in list_load
    elif isinstance(dict,value):
TypeError: isinstance() arg 2 must be a type or tuple of types

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\Project_python\api_cms\common\requests_util.py", line 187, in analysis_yaml
    res = self.send_request(name =name,method=method,
  File "E:\Project_python\api_cms\common\requests_util.py", line 325, in send_request
    error_log("发送请求异常：异常信息: %s" % str(traceback.format_exc()))
  File "E:\Project_python\api_cms\common\logger_util.py", line 66, in error_log
    raise Exception(log_message)
Exception: 发送请求异常：异常信息: Traceback (most recent call last):
  File "E:\Project_python\api_cms\common\requests_util.py", line 306, in send_request
    kwargs[key] = self.replace_load(value)
  File "E:\Project_python\api_cms\common\requests_util.py", line 152, in replace_load
    data = self.int_load(data)
  File "E:\Project_python\api_cms\common\requests_util.py", line 115, in int_load
    data = self.list_load(data)
  File "E:\Project_python\api_cms\common\requests_util.py", line 54, in list_load
    elif isinstance(dict,value):
TypeError: isinstance() arg 2 must be a type or tuple of types


[2023-08-23 10:45:32,239] logger_util.py->error_log line:65 [INFO] 发送请求异常：异常信息: Traceback (most recent call last):
  File "E:\Project_python\api_cms\common\requests_util.py", line 306, in send_request
    kwargs[key] = self.replace_load(value)
  File "E:\Project_python\api_cms\common\requests_util.py", line 152, in replace_load
    data = self.int_load(data)
  File "E:\Project_python\api_cms\common\requests_util.py", line 115, in int_load
    data = self.list_load(data)
  File "E:\Project_python\api_cms\common\requests_util.py", line 54, in list_load
    elif isinstance(dict,value):
TypeError: isinstance() arg 2 must be a type or tuple of types

[2023-08-23 10:45:32,239] logger_util.py->error_log line:65 [INFO] 分析YAML文件异常：异常信息: Traceback (most recent call last):
  File "E:\Project_python\api_cms\common\requests_util.py", line 306, in send_request
    kwargs[key] = self.replace_load(value)
  File "E:\Project_python\api_cms\common\requests_util.py", line 152, in replace_load
    data = self.int_load(data)
  File "E:\Project_python\api_cms\common\requests_util.py", line 115, in int_load
    data = self.list_load(data)
  File "E:\Project_python\api_cms\common\requests_util.py", line 54, in list_load
    elif isinstance(dict,value):
TypeError: isinstance() arg 2 must be a type or tuple of types

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\Project_python\api_cms\common\requests_util.py", line 187, in analysis_yaml
    res = self.send_request(name =name,method=method,
  File "E:\Project_python\api_cms\common\requests_util.py", line 325, in send_request
    error_log("发送请求异常：异常信息: %s" % str(traceback.format_exc()))
  File "E:\Project_python\api_cms\common\logger_util.py", line 66, in error_log
    raise Exception(log_message)
Exception: 发送请求异常：异常信息: Traceback (most recent call last):
  File "E:\Project_python\api_cms\common\requests_util.py", line 306, in send_request
    kwargs[key] = self.replace_load(value)
  File "E:\Project_python\api_cms\common\requests_util.py", line 152, in replace_load
    data = self.int_load(data)
  File "E:\Project_python\api_cms\common\requests_util.py", line 115, in int_load
    data = self.list_load(data)
  File "E:\Project_python\api_cms\common\requests_util.py", line 54, in list_load
    elif isinstance(dict,value):
TypeError: isinstance() arg 2 must be a type or tuple of types


