[2023-08-08 19:46:04,809] logger_util.py->write_log line:61 [INFO] -------------接口请求开始-----------
[2023-08-08 19:46:04,809] logger_util.py->write_log line:61 [INFO] 接口名称：创建工程
[2023-08-08 19:46:04,809] logger_util.py->write_log line:61 [INFO] 接口方式：post
[2023-08-08 19:46:04,810] logger_util.py->write_log line:61 [INFO] 接口路径：http://127.0.0.1:18000/api/v1/project/node
[2023-08-08 19:46:04,810] logger_util.py->write_log line:61 [INFO] 请求头：{}
[2023-08-08 19:46:04,810] logger_util.py->write_log line:61 [INFO] 请求参数：{'name': '工程236', 'path': 'C:\\Users\\Administrator\\Downloads', 'type': 1}
[2023-08-08 19:46:04,810] logger_util.py->write_log line:61 [INFO] 文件上传：None
[2023-08-08 19:46:05,127] logger_util.py->write_log line:61 [INFO] 预期结果：[{'equals': {'status_code': 200}}]
[2023-08-08 19:46:05,128] logger_util.py->write_log line:61 [INFO] 实际结果：16
[2023-08-08 19:46:05,128] logger_util.py->write_log line:61 [INFO] 接口请求成功！
[2023-08-08 19:46:05,128] logger_util.py->write_log line:61 [INFO] -------------接口请求结束-----------

[2023-08-08 19:46:05,161] logger_util.py->error_log line:65 [INFO] 发送请求异常：异常信息: Traceback (most recent call last):
  File "E:\Project_python\api_SIOT\common\requests_util.py", line 310, in send_request
    self.base_url = self.replace_load(self.base_url) + self.replace_load(url)
  File "E:\Project_python\api_SIOT\common\requests_util.py", line 150, in replace_load
    new_value = getattr(DubugTalk(), func_name)(*args_value.split(','))
  File "E:\Project_python\api_SIOT\debug_talk.py", line 21, in get_extract_data
    return read_extract_file(node_name)
  File "E:\Project_python\api_SIOT\common\yaml_util.py", line 19, in read_extract_file
    return value[one_node]
TypeError: 'NoneType' object is not subscriptable

[2023-08-08 19:46:05,162] logger_util.py->error_log line:65 [INFO] 分析YAML文件异常：异常信息: Traceback (most recent call last):
  File "E:\Project_python\api_SIOT\common\requests_util.py", line 310, in send_request
    self.base_url = self.replace_load(self.base_url) + self.replace_load(url)
  File "E:\Project_python\api_SIOT\common\requests_util.py", line 150, in replace_load
    new_value = getattr(DubugTalk(), func_name)(*args_value.split(','))
  File "E:\Project_python\api_SIOT\debug_talk.py", line 21, in get_extract_data
    return read_extract_file(node_name)
  File "E:\Project_python\api_SIOT\common\yaml_util.py", line 19, in read_extract_file
    return value[one_node]
TypeError: 'NoneType' object is not subscriptable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\Project_python\api_SIOT\common\requests_util.py", line 198, in analysis_yaml
    res = self.send_request(name =name,method=method,
  File "E:\Project_python\api_SIOT\common\requests_util.py", line 339, in send_request
    error_log("发送请求异常：异常信息: %s" % str(traceback.format_exc()))
  File "E:\Project_python\api_SIOT\common\logger_util.py", line 66, in error_log
    raise Exception(log_message)
Exception: 发送请求异常：异常信息: Traceback (most recent call last):
  File "E:\Project_python\api_SIOT\common\requests_util.py", line 310, in send_request
    self.base_url = self.replace_load(self.base_url) + self.replace_load(url)
  File "E:\Project_python\api_SIOT\common\requests_util.py", line 150, in replace_load
    new_value = getattr(DubugTalk(), func_name)(*args_value.split(','))
  File "E:\Project_python\api_SIOT\debug_talk.py", line 21, in get_extract_data
    return read_extract_file(node_name)
  File "E:\Project_python\api_SIOT\common\yaml_util.py", line 19, in read_extract_file
    return value[one_node]
TypeError: 'NoneType' object is not subscriptable


