[2024-01-16 05:47:56,200] logger_util.py->write_log line:61 [INFO] 
-------------接口请求开始-----------
[2024-01-16 05:47:56,200] logger_util.py->write_log line:61 [INFO] 接口名称：创建互联项
[2024-01-16 05:47:56,200] logger_util.py->write_log line:61 [INFO] 接口方式：post
[2024-01-16 05:47:56,201] logger_util.py->write_log line:61 [INFO] 接口路径：http://127.0.0.1:18000/api/v1/connection
[2024-01-16 05:47:56,201] logger_util.py->write_log line:61 [INFO] 请求头：{'X-Project': '67ebccb4a3b44b1a8a7df3f964ccbac7'}
[2024-01-16 05:47:56,201] logger_util.py->write_log line:61 [INFO] 请求参数：{'id': None, 'name': 'mysql9908', 'connectionType': 1, 'databaseType': 1, 'authenticationType': None, 'server': '127.0.0.1', 'port': '3306', 'database': 'TestDB', 'databasePath': '', 'userName': 'root', 'password': 'syc123', 'changedPassword': True, 'mqttType': None, 'pushType': None, 'timingPeriod': None, 'changingPeriod': None, 'cloudDeviceId': '', 'originalSecret': ''}
[2024-01-16 05:47:56,202] logger_util.py->write_log line:61 [INFO] 文件上传：None
[2024-01-16 05:47:56,233] logger_util.py->write_log line:61 [INFO] 预期结果：[{'equals': {'status_code': 200}}]
[2024-01-16 05:47:56,233] logger_util.py->write_log line:61 [INFO] 实际结果：{'data': {'id': 3, 'name': 'mysql9908', 'connectionType': 1, 'databaseType': 1, 'authenticationType': 0, 'server': '127.0.0.1', 'port': 3306, 'database': 'TestDB', 'databasePath': '', 'userName': 'root'}, 'message': ''}
[2024-01-16 05:47:56,233] logger_util.py->write_log line:61 [INFO] 接口请求成功！
[2024-01-16 05:47:56,233] logger_util.py->write_log line:61 [INFO] 
-------------接口请求结束-----------

[2024-01-16 05:47:56,243] logger_util.py->write_log line:61 [INFO] 
-------------接口请求开始-----------
[2024-01-16 05:47:56,244] logger_util.py->write_log line:61 [INFO] 接口名称：创建映射表-定时触发-插入
[2024-01-16 05:47:56,244] logger_util.py->write_log line:61 [INFO] 接口方式：post
[2024-01-16 05:47:56,244] logger_util.py->write_log line:61 [INFO] 接口路径：http://127.0.0.1:18000/api/v1/connection/3/table
[2024-01-16 05:47:56,244] logger_util.py->write_log line:61 [INFO] 请求头：{'X-Project': '67ebccb4a3b44b1a8a7df3f964ccbac7'}
[2024-01-16 05:47:56,244] logger_util.py->write_log line:61 [INFO] 请求参数：{'isBasic': True, 'databaseTableName': 'student', 'querySql': '', 'name': '定时_插入1592'}
[2024-01-16 05:47:56,244] logger_util.py->write_log line:61 [INFO] 文件上传：None
[2024-01-16 05:47:56,270] logger_util.py->write_log line:61 [INFO] 预期结果：[{'equals': {'status_code': 200}}]
[2024-01-16 05:47:56,270] logger_util.py->write_log line:61 [INFO] 实际结果：{'id': 8, 'name': '定时_插入1592', 'connectionItemId': 3, 'fields': [{'tableName': 'student', 'tableAlias': '', 'columnName': 'id', 'displayName': 'id', 'dataTypeName': 'Int32', 'databaseTypeName': 'Int32', 'isValueType': True, 'isAsterisk': True}, {'tableName': 'student', 'tableAlias': '', 'columnName': 'time', 'displayName': 'time', 'dataTypeName': 'DateTime', 'databaseTypeName': 'DateTime', 'isValueType': False, 'isAsterisk': True}, {'tableName': 'student', 'tableAlias': '', 'columnName': 'name', 'displayName': 'name', 'dataTypeName': 'String', 'databaseTypeName': 'VarChar', 'isValueType': False, 'isAsterisk': True}, {'tableName': 'student', 'tableAlias': '', 'columnName': 'age', 'displayName': 'age', 'dataTypeName': 'Int32', 'databaseTypeName': 'Int32', 'isValueType': True, 'isAsterisk': True}, {'tableName': 'student', 'tableAlias': '', 'columnName': 'money', 'displayName': 'money', 'dataTypeName': 'Single', 'databaseTypeName': 'Float', 'isValueType': True, 'isAsterisk': True}], 'isBasic': True, 'basicDatabaseTableName': 'student', 'querySql': 'select * from `student`', 'detail': None, 'action': None, 'status': 1, 'prevStatus': 0, 'lastErrorMsg': None, 'lastErrorDateTime': None}
[2024-01-16 05:47:56,271] logger_util.py->write_log line:61 [INFO] 接口请求成功！
[2024-01-16 05:47:56,271] logger_util.py->write_log line:61 [INFO] 
-------------接口请求结束-----------

[2024-01-16 05:47:57,295] logger_util.py->write_log line:61 [INFO] 
-------------接口请求开始-----------
[2024-01-16 05:47:57,295] logger_util.py->write_log line:61 [INFO] 接口名称：保存配置-插入
[2024-01-16 05:47:57,296] logger_util.py->write_log line:61 [INFO] 接口方式：put
[2024-01-16 05:47:57,296] logger_util.py->write_log line:61 [INFO] 接口路径：http://127.0.0.1:18000/api/v1/connection/table/8/save
[2024-01-16 05:47:57,296] logger_util.py->write_log line:61 [INFO] 请求头：{'X-Project': '67ebccb4a3b44b1a8a7df3f964ccbac7'}
[2024-01-16 05:47:57,296] logger_util.py->write_log line:61 [INFO] 请求参数：{'actionType': 2, 'filters': [], 'sorts': [{'field': 'id', 'sortType': 2}], 'mappings': [{'field': 'time', 'relativeVariable': 'aa16', 'dataType': '日期时间', 'order': 1}, {'field': 'name', 'relativeVariable': 'A12', 'dataType': '字符串', 'order': 2}, {'field': 'age', 'relativeVariable': 'A2', 'dataType': '有符号8位整型', 'order': 3}, {'field': 'money', 'relativeVariable': 'A10', 'dataType': 'F32位浮点数IEEE754', 'order': 4}]}
[2024-01-16 05:47:57,296] logger_util.py->write_log line:61 [INFO] 文件上传：None
[2024-01-16 05:47:57,327] logger_util.py->write_log line:61 [INFO] 预期结果：[{'equals': {'status_code': 200}}]
[2024-01-16 05:47:57,327] logger_util.py->write_log line:61 [INFO] 实际结果：{'id': 8, 'name': '定时_插入1592', 'connectionItemId': 3, 'fields': [{'tableName': 'student', 'tableAlias': '', 'columnName': 'id', 'displayName': 'id', 'dataTypeName': 'Int32', 'databaseTypeName': 'Int32', 'isValueType': True, 'isAsterisk': True}, {'tableName': 'student', 'tableAlias': '', 'columnName': 'time', 'displayName': 'time', 'dataTypeName': 'DateTime', 'databaseTypeName': 'DateTime', 'isValueType': False, 'isAsterisk': True}, {'tableName': 'student', 'tableAlias': '', 'columnName': 'name', 'displayName': 'name', 'dataTypeName': 'String', 'databaseTypeName': 'VarChar', 'isValueType': False, 'isAsterisk': True}, {'tableName': 'student', 'tableAlias': '', 'columnName': 'age', 'displayName': 'age', 'dataTypeName': 'Int32', 'databaseTypeName': 'Int32', 'isValueType': True, 'isAsterisk': True}, {'tableName': 'student', 'tableAlias': '', 'columnName': 'money', 'displayName': 'money', 'dataTypeName': 'Single', 'databaseTypeName': 'Float', 'isValueType': True, 'isAsterisk': True}], 'isBasic': True, 'basicDatabaseTableName': 'student', 'querySql': 'select * from `student`', 'detail': {'actionType': 2, 'filters': [], 'sorts': [{'displayName': 'id', 'sortType': 2}], 'mapping': {'pendingDisplayNameRelativeVariable': None, 'ioMappings': [{'displayName': 'name', 'relativeVariable': 'A12', 'dataType': 16384, 'order': 2}, {'displayName': 'age', 'relativeVariable': 'A2', 'dataType': 2, 'order': 3}, {'displayName': 'money', 'relativeVariable': 'A10', 'dataType': 512, 'order': 4}], 'innerMappings': [{'displayName': 'time', 'relativeVariable': 'aa16', 'dataType': 8192, 'order': 1}], 'systemMappings': []}}, 'action': {'actionType': 2, 'mainSql': 'insert into `student` (`name`,`age`,`money`,`time`) values ({0},{1},{2},{3})', 'sortSql': '`id` desc', 'filterSql': '', 'mainSqlParams': [{'key': 'A12', 'value': False}, {'key': 'A2', 'value': True}, {'key': 'A10', 'value': True}, {'key': 'aa16', 'value': False}], 'filterSqlParams': [], 'assignment': None}, 'status': 1, 'prevStatus': 0, 'lastErrorMsg': None, 'lastErrorDateTime': None}
[2024-01-16 05:47:57,327] logger_util.py->write_log line:61 [INFO] 接口请求成功！
[2024-01-16 05:47:57,327] logger_util.py->write_log line:61 [INFO] 
-------------接口请求结束-----------

[2024-01-16 05:47:58,340] logger_util.py->write_log line:61 [INFO] 
-------------接口请求开始-----------
[2024-01-16 05:47:58,340] logger_util.py->write_log line:61 [INFO] 接口名称：触发配置-定时
[2024-01-16 05:47:58,340] logger_util.py->write_log line:61 [INFO] 接口方式：put
[2024-01-16 05:47:58,341] logger_util.py->write_log line:61 [INFO] 接口路径：http://127.0.0.1:18000/api/v1/connection/table/8/trigger/save
[2024-01-16 05:47:58,341] logger_util.py->write_log line:61 [INFO] 请求头：{'X-Project': '67ebccb4a3b44b1a8a7df3f964ccbac7'}
[2024-01-16 05:47:58,341] logger_util.py->write_log line:61 [INFO] 请求参数：[{'effectiveDateTime': '2023-11-28T06:55:22.000Z', 'frequencyValue': 1, 'frequencyUnit': 1, 'matchAll': True, 'condition': 'A2>10', 'conditionDetail': 1, 'frequencyCheck': False, 'alarmPointIds': [], 'triggerType': 1}]
[2024-01-16 05:47:58,341] logger_util.py->write_log line:61 [INFO] 文件上传：None
[2024-01-16 05:47:58,372] logger_util.py->write_log line:61 [INFO] 预期结果：[{'equals': {'status_code': 200}}]
[2024-01-16 05:47:58,372] logger_util.py->write_log line:61 [INFO] 实际结果：
[2024-01-16 05:47:58,372] logger_util.py->write_log line:61 [INFO] 接口请求成功！
[2024-01-16 05:47:58,372] logger_util.py->write_log line:61 [INFO] 
-------------接口请求结束-----------

[2024-01-16 05:47:59,385] logger_util.py->write_log line:61 [INFO] 
-------------接口请求开始-----------
[2024-01-16 05:47:59,385] logger_util.py->write_log line:61 [INFO] 接口名称：刷新-定时触发-插入
[2024-01-16 05:47:59,385] logger_util.py->write_log line:61 [INFO] 接口方式：get
[2024-01-16 05:47:59,385] logger_util.py->write_log line:61 [INFO] 接口路径：http://127.0.0.1:18000/api/v1/connection/table/8/preview
[2024-01-16 05:47:59,385] logger_util.py->write_log line:61 [INFO] 请求头：{'X-Project': '67ebccb4a3b44b1a8a7df3f964ccbac7'}
[2024-01-16 05:47:59,385] logger_util.py->write_log line:61 [INFO] 文件上传：None
[2024-01-16 05:47:59,402] logger_util.py->error_log line:65 [INFO] 断言失败：返回结果中不存在：age
[2024-01-16 05:47:59,402] logger_util.py->write_log line:61 [INFO] 实际结果：{'status': 1, 'lastErrorMsg': None, 'total': 0, 'headers': ['id', 'time', 'name', 'age', 'money'], 'data': []}
[2024-01-16 05:47:59,402] logger_util.py->write_log line:61 [INFO] 接口请求失败！
[2024-01-16 05:47:59,402] logger_util.py->write_log line:61 [INFO] -------------接口请求结束-----------

[2024-01-16 05:47:59,403] logger_util.py->error_log line:65 [INFO] 断言异常：异常信息: Traceback (most recent call last):
  File "E:\Project_python\api_cms\common\requests_util.py", line 384, in validate_result
    error_log("断言失败：返回结果中不存在："+assert_key)
  File "E:\Project_python\api_cms\common\logger_util.py", line 66, in error_log
    raise Exception(log_message)
Exception: 断言失败：返回结果中不存在：age

[2024-01-16 05:47:59,403] logger_util.py->error_log line:65 [INFO] 分析YAML文件异常：异常信息: Traceback (most recent call last):
  File "E:\Project_python\api_cms\common\requests_util.py", line 384, in validate_result
    error_log("断言失败：返回结果中不存在："+assert_key)
  File "E:\Project_python\api_cms\common\logger_util.py", line 66, in error_log
    raise Exception(log_message)
Exception: 断言失败：返回结果中不存在：age

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\Project_python\api_cms\common\requests_util.py", line 248, in analysis_yaml
    self.validate_result(yq_result, return_data, status_code)
  File "E:\Project_python\api_cms\common\requests_util.py", line 448, in validate_result
    error_log("断言异常：异常信息: %s" % str(traceback.format_exc()))
  File "E:\Project_python\api_cms\common\logger_util.py", line 66, in error_log
    raise Exception(log_message)
Exception: 断言异常：异常信息: Traceback (most recent call last):
  File "E:\Project_python\api_cms\common\requests_util.py", line 384, in validate_result
    error_log("断言失败：返回结果中不存在："+assert_key)
  File "E:\Project_python\api_cms\common\logger_util.py", line 66, in error_log
    raise Exception(log_message)
Exception: 断言失败：返回结果中不存在：age


[2024-01-16 05:47:59,577] logger_util.py->write_log line:61 [INFO] 
-------------接口请求开始-----------
[2024-01-16 05:47:59,577] logger_util.py->write_log line:61 [INFO] 接口名称：禁用定时插入映射表
[2024-01-16 05:47:59,577] logger_util.py->write_log line:61 [INFO] 接口方式：put
[2024-01-16 05:47:59,577] logger_util.py->write_log line:61 [INFO] 接口路径：http://127.0.0.1:18000/api/v1/connection/switch/2/8/off
[2024-01-16 05:47:59,577] logger_util.py->write_log line:61 [INFO] 请求头：{'X-Project': '67ebccb4a3b44b1a8a7df3f964ccbac7'}
[2024-01-16 05:47:59,577] logger_util.py->write_log line:61 [INFO] 文件上传：None
[2024-01-16 05:47:59,606] logger_util.py->write_log line:61 [INFO] 预期结果：[{'equals': {'status_code': 200}}]
[2024-01-16 05:47:59,606] logger_util.py->write_log line:61 [INFO] 实际结果：[{'nodeGuid': '44d9dd32-ef18-486a-a2a2-6d0782f99d56', 'id': 8, 'type': 2, 'name': '定时_插入1592', 'status': 2, 'errorMsg': None, 'children': []}]
[2024-01-16 05:47:59,606] logger_util.py->write_log line:61 [INFO] 接口请求成功！
[2024-01-16 05:47:59,606] logger_util.py->write_log line:61 [INFO] 
-------------接口请求结束-----------

[2024-01-16 05:48:00,622] logger_util.py->write_log line:61 [INFO] 
-------------接口请求开始-----------
[2024-01-16 05:48:00,623] logger_util.py->write_log line:61 [INFO] 接口名称：创建映射表-变量触发-插入
[2024-01-16 05:48:00,623] logger_util.py->write_log line:61 [INFO] 接口方式：post
[2024-01-16 05:48:00,623] logger_util.py->write_log line:61 [INFO] 接口路径：http://127.0.0.1:18000/api/v1/connection/3/table
[2024-01-16 05:48:00,623] logger_util.py->write_log line:61 [INFO] 请求头：{'X-Project': '67ebccb4a3b44b1a8a7df3f964ccbac7'}
[2024-01-16 05:48:00,623] logger_util.py->write_log line:61 [INFO] 请求参数：{'isBasic': True, 'databaseTableName': 'student', 'querySql': '', 'name': '变量触发_插入5489'}
[2024-01-16 05:48:00,623] logger_util.py->write_log line:61 [INFO] 文件上传：None
[2024-01-16 05:48:00,649] logger_util.py->write_log line:61 [INFO] 预期结果：[{'equals': {'status_code': 200}}]
[2024-01-16 05:48:00,649] logger_util.py->write_log line:61 [INFO] 实际结果：{'id': 9, 'name': '变量触发_插入5489', 'connectionItemId': 3, 'fields': [{'tableName': 'student', 'tableAlias': '', 'columnName': 'id', 'displayName': 'id', 'dataTypeName': 'Int32', 'databaseTypeName': 'Int32', 'isValueType': True, 'isAsterisk': True}, {'tableName': 'student', 'tableAlias': '', 'columnName': 'time', 'displayName': 'time', 'dataTypeName': 'DateTime', 'databaseTypeName': 'DateTime', 'isValueType': False, 'isAsterisk': True}, {'tableName': 'student', 'tableAlias': '', 'columnName': 'name', 'displayName': 'name', 'dataTypeName': 'String', 'databaseTypeName': 'VarChar', 'isValueType': False, 'isAsterisk': True}, {'tableName': 'student', 'tableAlias': '', 'columnName': 'age', 'displayName': 'age', 'dataTypeName': 'Int32', 'databaseTypeName': 'Int32', 'isValueType': True, 'isAsterisk': True}, {'tableName': 'student', 'tableAlias': '', 'columnName': 'money', 'displayName': 'money', 'dataTypeName': 'Single', 'databaseTypeName': 'Float', 'isValueType': True, 'isAsterisk': True}], 'isBasic': True, 'basicDatabaseTableName': 'student', 'querySql': 'select * from `student`', 'detail': None, 'action': None, 'status': 1, 'prevStatus': 0, 'lastErrorMsg': None, 'lastErrorDateTime': None}
[2024-01-16 05:48:00,650] logger_util.py->write_log line:61 [INFO] 接口请求成功！
[2024-01-16 05:48:00,650] logger_util.py->write_log line:61 [INFO] 
-------------接口请求结束-----------

[2024-01-16 05:48:02,663] logger_util.py->write_log line:61 [INFO] 
-------------接口请求开始-----------
[2024-01-16 05:48:02,663] logger_util.py->write_log line:61 [INFO] 接口名称：保存配置-插入
[2024-01-16 05:48:02,663] logger_util.py->write_log line:61 [INFO] 接口方式：put
[2024-01-16 05:48:02,664] logger_util.py->write_log line:61 [INFO] 接口路径：http://127.0.0.1:18000/api/v1/connection/table/9/save
[2024-01-16 05:48:02,664] logger_util.py->write_log line:61 [INFO] 请求头：{'X-Project': '67ebccb4a3b44b1a8a7df3f964ccbac7'}
[2024-01-16 05:48:02,664] logger_util.py->write_log line:61 [INFO] 请求参数：{'actionType': 2, 'filters': [], 'sorts': [{'field': 'id', 'sortType': 2}], 'mappings': [{'field': 'time', 'relativeVariable': 'aa16', 'dataType': '日期时间', 'order': 1}, {'field': 'name', 'relativeVariable': 'A12', 'dataType': '字符串', 'order': 2}, {'field': 'age', 'relativeVariable': 'A2', 'dataType': '有符号8位整型', 'order': 3}, {'field': 'money', 'relativeVariable': 'A10', 'dataType': 'F32位浮点数IEEE754', 'order': 4}]}
[2024-01-16 05:48:02,664] logger_util.py->write_log line:61 [INFO] 文件上传：None
[2024-01-16 05:48:02,695] logger_util.py->write_log line:61 [INFO] 预期结果：[{'equals': {'status_code': 200}}]
[2024-01-16 05:48:02,695] logger_util.py->write_log line:61 [INFO] 实际结果：{'id': 9, 'name': '变量触发_插入5489', 'connectionItemId': 3, 'fields': [{'tableName': 'student', 'tableAlias': '', 'columnName': 'id', 'displayName': 'id', 'dataTypeName': 'Int32', 'databaseTypeName': 'Int32', 'isValueType': True, 'isAsterisk': True}, {'tableName': 'student', 'tableAlias': '', 'columnName': 'time', 'displayName': 'time', 'dataTypeName': 'DateTime', 'databaseTypeName': 'DateTime', 'isValueType': False, 'isAsterisk': True}, {'tableName': 'student', 'tableAlias': '', 'columnName': 'name', 'displayName': 'name', 'dataTypeName': 'String', 'databaseTypeName': 'VarChar', 'isValueType': False, 'isAsterisk': True}, {'tableName': 'student', 'tableAlias': '', 'columnName': 'age', 'displayName': 'age', 'dataTypeName': 'Int32', 'databaseTypeName': 'Int32', 'isValueType': True, 'isAsterisk': True}, {'tableName': 'student', 'tableAlias': '', 'columnName': 'money', 'displayName': 'money', 'dataTypeName': 'Single', 'databaseTypeName': 'Float', 'isValueType': True, 'isAsterisk': True}], 'isBasic': True, 'basicDatabaseTableName': 'student', 'querySql': 'select * from `student`', 'detail': {'actionType': 2, 'filters': [], 'sorts': [{'displayName': 'id', 'sortType': 2}], 'mapping': {'pendingDisplayNameRelativeVariable': None, 'ioMappings': [{'displayName': 'name', 'relativeVariable': 'A12', 'dataType': 16384, 'order': 2}, {'displayName': 'age', 'relativeVariable': 'A2', 'dataType': 2, 'order': 3}, {'displayName': 'money', 'relativeVariable': 'A10', 'dataType': 512, 'order': 4}], 'innerMappings': [{'displayName': 'time', 'relativeVariable': 'aa16', 'dataType': 8192, 'order': 1}], 'systemMappings': []}}, 'action': {'actionType': 2, 'mainSql': 'insert into `student` (`name`,`age`,`money`,`time`) values ({0},{1},{2},{3})', 'sortSql': '`id` desc', 'filterSql': '', 'mainSqlParams': [{'key': 'A12', 'value': False}, {'key': 'A2', 'value': True}, {'key': 'A10', 'value': True}, {'key': 'aa16', 'value': False}], 'filterSqlParams': [], 'assignment': None}, 'status': 1, 'prevStatus': 0, 'lastErrorMsg': None, 'lastErrorDateTime': None}
[2024-01-16 05:48:02,695] logger_util.py->write_log line:61 [INFO] 接口请求成功！
[2024-01-16 05:48:02,696] logger_util.py->write_log line:61 [INFO] 
-------------接口请求结束-----------

[2024-01-16 05:48:04,708] logger_util.py->write_log line:61 [INFO] 
-------------接口请求开始-----------
[2024-01-16 05:48:04,708] logger_util.py->write_log line:61 [INFO] 接口名称：触发配置-变量触发
[2024-01-16 05:48:04,708] logger_util.py->write_log line:61 [INFO] 接口方式：put
[2024-01-16 05:48:04,708] logger_util.py->write_log line:61 [INFO] 接口路径：http://127.0.0.1:18000/api/v1/connection/table/9/trigger/save
[2024-01-16 05:48:04,708] logger_util.py->write_log line:61 [INFO] 请求头：{'X-Project': '67ebccb4a3b44b1a8a7df3f964ccbac7'}
[2024-01-16 05:48:04,708] logger_util.py->write_log line:61 [INFO] 请求参数：[{'effectiveDateTime': '', 'frequencyValue': 1, 'frequencyUnit': 1, 'matchAll': False, 'condition': 'A1', 'conditionDetail': 1, 'frequencyCheck': False, 'alarmPointIds': [], 'triggerType': 2}]
[2024-01-16 05:48:04,708] logger_util.py->write_log line:61 [INFO] 文件上传：None
[2024-01-16 05:48:04,739] logger_util.py->write_log line:61 [INFO] 预期结果：[{'equals': {'status_code': 200}}]
[2024-01-16 05:48:04,740] logger_util.py->write_log line:61 [INFO] 实际结果：
[2024-01-16 05:48:04,740] logger_util.py->write_log line:61 [INFO] 接口请求成功！
[2024-01-16 05:48:04,740] logger_util.py->write_log line:61 [INFO] 
-------------接口请求结束-----------

[2024-01-16 05:48:06,826] logger_util.py->error_log line:65 [INFO] 发送请求异常：异常信息: Traceback (most recent call last):
  File "E:\Project_python\api_cms\common\requests_util.py", line 312, in send_request
    self.last_headers = self.replace_load(headers)
  File "E:\Project_python\api_cms\common\requests_util.py", line 140, in replace_load
    new_value = getattr(DubugTalk(), func_name)(*args_value.split(','))
  File "E:\Project_python\api_cms\debug_talk.py", line 26, in get_extract_data
    return read_extract_file(node_name)
  File "E:\Project_python\api_cms\common\yaml_util.py", line 19, in read_extract_file
    return value[one_node]
KeyError: 'Authorization'

[2024-01-16 05:48:06,826] logger_util.py->error_log line:65 [INFO] 分析YAML文件异常：异常信息: Traceback (most recent call last):
  File "E:\Project_python\api_cms\common\requests_util.py", line 312, in send_request
    self.last_headers = self.replace_load(headers)
  File "E:\Project_python\api_cms\common\requests_util.py", line 140, in replace_load
    new_value = getattr(DubugTalk(), func_name)(*args_value.split(','))
  File "E:\Project_python\api_cms\debug_talk.py", line 26, in get_extract_data
    return read_extract_file(node_name)
  File "E:\Project_python\api_cms\common\yaml_util.py", line 19, in read_extract_file
    return value[one_node]
KeyError: 'Authorization'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\Project_python\api_cms\common\requests_util.py", line 185, in analysis_yaml
    res = self.send_request(name =name,method=method,
  File "E:\Project_python\api_cms\common\requests_util.py", line 335, in send_request
    error_log("发送请求异常：异常信息: %s" % str(traceback.format_exc()))
  File "E:\Project_python\api_cms\common\logger_util.py", line 66, in error_log
    raise Exception(log_message)
Exception: 发送请求异常：异常信息: Traceback (most recent call last):
  File "E:\Project_python\api_cms\common\requests_util.py", line 312, in send_request
    self.last_headers = self.replace_load(headers)
  File "E:\Project_python\api_cms\common\requests_util.py", line 140, in replace_load
    new_value = getattr(DubugTalk(), func_name)(*args_value.split(','))
  File "E:\Project_python\api_cms\debug_talk.py", line 26, in get_extract_data
    return read_extract_file(node_name)
  File "E:\Project_python\api_cms\common\yaml_util.py", line 19, in read_extract_file
    return value[one_node]
KeyError: 'Authorization'


[2024-01-16 05:48:06,865] logger_util.py->error_log line:65 [INFO] 发送请求异常：异常信息: Traceback (most recent call last):
  File "E:\Project_python\api_cms\common\requests_util.py", line 312, in send_request
    self.last_headers = self.replace_load(headers)
  File "E:\Project_python\api_cms\common\requests_util.py", line 140, in replace_load
    new_value = getattr(DubugTalk(), func_name)(*args_value.split(','))
  File "E:\Project_python\api_cms\debug_talk.py", line 26, in get_extract_data
    return read_extract_file(node_name)
  File "E:\Project_python\api_cms\common\yaml_util.py", line 19, in read_extract_file
    return value[one_node]
KeyError: 'Authorization'

[2024-01-16 05:48:06,866] logger_util.py->error_log line:65 [INFO] 分析YAML文件异常：异常信息: Traceback (most recent call last):
  File "E:\Project_python\api_cms\common\requests_util.py", line 312, in send_request
    self.last_headers = self.replace_load(headers)
  File "E:\Project_python\api_cms\common\requests_util.py", line 140, in replace_load
    new_value = getattr(DubugTalk(), func_name)(*args_value.split(','))
  File "E:\Project_python\api_cms\debug_talk.py", line 26, in get_extract_data
    return read_extract_file(node_name)
  File "E:\Project_python\api_cms\common\yaml_util.py", line 19, in read_extract_file
    return value[one_node]
KeyError: 'Authorization'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\Project_python\api_cms\common\requests_util.py", line 185, in analysis_yaml
    res = self.send_request(name =name,method=method,
  File "E:\Project_python\api_cms\common\requests_util.py", line 335, in send_request
    error_log("发送请求异常：异常信息: %s" % str(traceback.format_exc()))
  File "E:\Project_python\api_cms\common\logger_util.py", line 66, in error_log
    raise Exception(log_message)
Exception: 发送请求异常：异常信息: Traceback (most recent call last):
  File "E:\Project_python\api_cms\common\requests_util.py", line 312, in send_request
    self.last_headers = self.replace_load(headers)
  File "E:\Project_python\api_cms\common\requests_util.py", line 140, in replace_load
    new_value = getattr(DubugTalk(), func_name)(*args_value.split(','))
  File "E:\Project_python\api_cms\debug_talk.py", line 26, in get_extract_data
    return read_extract_file(node_name)
  File "E:\Project_python\api_cms\common\yaml_util.py", line 19, in read_extract_file
    return value[one_node]
KeyError: 'Authorization'


[2024-01-16 05:48:06,904] logger_util.py->write_log line:61 [INFO] 
-------------接口请求开始-----------
[2024-01-16 05:48:06,904] logger_util.py->write_log line:61 [INFO] 接口名称：刷新-变量触发-插入
[2024-01-16 05:48:06,904] logger_util.py->write_log line:61 [INFO] 接口方式：get
[2024-01-16 05:48:06,904] logger_util.py->write_log line:61 [INFO] 接口路径：http://127.0.0.1:18000/api/v1/connection/table/9/preview
[2024-01-16 05:48:06,904] logger_util.py->write_log line:61 [INFO] 请求头：{'X-Project': '67ebccb4a3b44b1a8a7df3f964ccbac7'}
[2024-01-16 05:48:06,905] logger_util.py->write_log line:61 [INFO] 文件上传：None
[2024-01-16 05:48:06,913] logger_util.py->error_log line:65 [INFO] 断言失败：返回结果中不存在：age
[2024-01-16 05:48:06,913] logger_util.py->write_log line:61 [INFO] 实际结果：{'status': 1, 'lastErrorMsg': None, 'total': 0, 'headers': ['id', 'time', 'name', 'age', 'money'], 'data': []}
[2024-01-16 05:48:06,913] logger_util.py->write_log line:61 [INFO] 接口请求失败！
[2024-01-16 05:48:06,913] logger_util.py->write_log line:61 [INFO] -------------接口请求结束-----------

[2024-01-16 05:48:06,914] logger_util.py->error_log line:65 [INFO] 断言异常：异常信息: Traceback (most recent call last):
  File "E:\Project_python\api_cms\common\requests_util.py", line 384, in validate_result
    error_log("断言失败：返回结果中不存在："+assert_key)
  File "E:\Project_python\api_cms\common\logger_util.py", line 66, in error_log
    raise Exception(log_message)
Exception: 断言失败：返回结果中不存在：age

[2024-01-16 05:48:06,914] logger_util.py->error_log line:65 [INFO] 分析YAML文件异常：异常信息: Traceback (most recent call last):
  File "E:\Project_python\api_cms\common\requests_util.py", line 384, in validate_result
    error_log("断言失败：返回结果中不存在："+assert_key)
  File "E:\Project_python\api_cms\common\logger_util.py", line 66, in error_log
    raise Exception(log_message)
Exception: 断言失败：返回结果中不存在：age

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\Project_python\api_cms\common\requests_util.py", line 248, in analysis_yaml
    self.validate_result(yq_result, return_data, status_code)
  File "E:\Project_python\api_cms\common\requests_util.py", line 448, in validate_result
    error_log("断言异常：异常信息: %s" % str(traceback.format_exc()))
  File "E:\Project_python\api_cms\common\logger_util.py", line 66, in error_log
    raise Exception(log_message)
Exception: 断言异常：异常信息: Traceback (most recent call last):
  File "E:\Project_python\api_cms\common\requests_util.py", line 384, in validate_result
    error_log("断言失败：返回结果中不存在："+assert_key)
  File "E:\Project_python\api_cms\common\logger_util.py", line 66, in error_log
    raise Exception(log_message)
Exception: 断言失败：返回结果中不存在：age


[2024-01-16 05:48:07,031] logger_util.py->write_log line:61 [INFO] 
-------------接口请求开始-----------
[2024-01-16 05:48:07,032] logger_util.py->write_log line:61 [INFO] 接口名称：禁用变量插入映射表
[2024-01-16 05:48:07,032] logger_util.py->write_log line:61 [INFO] 接口方式：put
[2024-01-16 05:48:07,032] logger_util.py->write_log line:61 [INFO] 接口路径：http://127.0.0.1:18000/api/v1/connection/switch/2/9/off
[2024-01-16 05:48:07,032] logger_util.py->write_log line:61 [INFO] 请求头：{'X-Project': '67ebccb4a3b44b1a8a7df3f964ccbac7'}
[2024-01-16 05:48:07,032] logger_util.py->write_log line:61 [INFO] 文件上传：None
[2024-01-16 05:48:07,060] logger_util.py->write_log line:61 [INFO] 预期结果：[{'equals': {'status_code': 200}}]
[2024-01-16 05:48:07,060] logger_util.py->write_log line:61 [INFO] 实际结果：[{'nodeGuid': '3de8607c-81f7-44f3-8d56-2156542dd943', 'id': 9, 'type': 2, 'name': '变量触发_插入5489', 'status': 2, 'errorMsg': None, 'children': []}]
[2024-01-16 05:48:07,060] logger_util.py->write_log line:61 [INFO] 接口请求成功！
[2024-01-16 05:48:07,060] logger_util.py->write_log line:61 [INFO] 
-------------接口请求结束-----------

[2024-01-16 05:48:07,068] logger_util.py->write_log line:61 [INFO] 
-------------接口请求开始-----------
[2024-01-16 05:48:07,068] logger_util.py->write_log line:61 [INFO] 接口名称：创建映射表-报警触发-插入
[2024-01-16 05:48:07,068] logger_util.py->write_log line:61 [INFO] 接口方式：post
[2024-01-16 05:48:07,068] logger_util.py->write_log line:61 [INFO] 接口路径：http://127.0.0.1:18000/api/v1/connection/3/table
[2024-01-16 05:48:07,068] logger_util.py->write_log line:61 [INFO] 请求头：{'X-Project': '67ebccb4a3b44b1a8a7df3f964ccbac7'}
[2024-01-16 05:48:07,068] logger_util.py->write_log line:61 [INFO] 请求参数：{'isBasic': True, 'databaseTableName': 'student', 'querySql': '', 'name': '报警触发_插入7471'}
[2024-01-16 05:48:07,068] logger_util.py->write_log line:61 [INFO] 文件上传：None
[2024-01-16 05:48:07,099] logger_util.py->write_log line:61 [INFO] 预期结果：[{'equals': {'status_code': 200}}]
[2024-01-16 05:48:07,099] logger_util.py->write_log line:61 [INFO] 实际结果：{'id': 10, 'name': '报警触发_插入7471', 'connectionItemId': 3, 'fields': [{'tableName': 'student', 'tableAlias': '', 'columnName': 'id', 'displayName': 'id', 'dataTypeName': 'Int32', 'databaseTypeName': 'Int32', 'isValueType': True, 'isAsterisk': True}, {'tableName': 'student', 'tableAlias': '', 'columnName': 'time', 'displayName': 'time', 'dataTypeName': 'DateTime', 'databaseTypeName': 'DateTime', 'isValueType': False, 'isAsterisk': True}, {'tableName': 'student', 'tableAlias': '', 'columnName': 'name', 'displayName': 'name', 'dataTypeName': 'String', 'databaseTypeName': 'VarChar', 'isValueType': False, 'isAsterisk': True}, {'tableName': 'student', 'tableAlias': '', 'columnName': 'age', 'displayName': 'age', 'dataTypeName': 'Int32', 'databaseTypeName': 'Int32', 'isValueType': True, 'isAsterisk': True}, {'tableName': 'student', 'tableAlias': '', 'columnName': 'money', 'displayName': 'money', 'dataTypeName': 'Single', 'databaseTypeName': 'Float', 'isValueType': True, 'isAsterisk': True}], 'isBasic': True, 'basicDatabaseTableName': 'student', 'querySql': 'select * from `student`', 'detail': None, 'action': None, 'status': 1, 'prevStatus': 0, 'lastErrorMsg': None, 'lastErrorDateTime': None}
[2024-01-16 05:48:07,099] logger_util.py->write_log line:61 [INFO] 接口请求成功！
[2024-01-16 05:48:07,099] logger_util.py->write_log line:61 [INFO] 
-------------接口请求结束-----------

[2024-01-16 05:48:09,117] logger_util.py->write_log line:61 [INFO] 
-------------接口请求开始-----------
[2024-01-16 05:48:09,117] logger_util.py->write_log line:61 [INFO] 接口名称：保存配置-插入
[2024-01-16 05:48:09,118] logger_util.py->write_log line:61 [INFO] 接口方式：put
[2024-01-16 05:48:09,118] logger_util.py->write_log line:61 [INFO] 接口路径：http://127.0.0.1:18000/api/v1/connection/table/10/save
[2024-01-16 05:48:09,118] logger_util.py->write_log line:61 [INFO] 请求头：{'X-Project': '67ebccb4a3b44b1a8a7df3f964ccbac7'}
[2024-01-16 05:48:09,118] logger_util.py->write_log line:61 [INFO] 请求参数：{'actionType': 2, 'filters': [], 'sorts': [{'field': 'id', 'sortType': 2}], 'mappings': [{'field': 'time', 'relativeVariable': 'aa16', 'dataType': '日期时间', 'order': 1}, {'field': 'name', 'relativeVariable': 'A12', 'dataType': '字符串', 'order': 2}, {'field': 'age', 'relativeVariable': 'A2', 'dataType': '有符号8位整型', 'order': 3}, {'field': 'money', 'relativeVariable': 'A10', 'dataType': 'F32位浮点数IEEE754', 'order': 4}]}
[2024-01-16 05:48:09,118] logger_util.py->write_log line:61 [INFO] 文件上传：None
[2024-01-16 05:48:09,153] logger_util.py->write_log line:61 [INFO] 预期结果：[{'equals': {'status_code': 200}}]
[2024-01-16 05:48:09,153] logger_util.py->write_log line:61 [INFO] 实际结果：{'id': 10, 'name': '报警触发_插入7471', 'connectionItemId': 3, 'fields': [{'tableName': 'student', 'tableAlias': '', 'columnName': 'id', 'displayName': 'id', 'dataTypeName': 'Int32', 'databaseTypeName': 'Int32', 'isValueType': True, 'isAsterisk': True}, {'tableName': 'student', 'tableAlias': '', 'columnName': 'time', 'displayName': 'time', 'dataTypeName': 'DateTime', 'databaseTypeName': 'DateTime', 'isValueType': False, 'isAsterisk': True}, {'tableName': 'student', 'tableAlias': '', 'columnName': 'name', 'displayName': 'name', 'dataTypeName': 'String', 'databaseTypeName': 'VarChar', 'isValueType': False, 'isAsterisk': True}, {'tableName': 'student', 'tableAlias': '', 'columnName': 'age', 'displayName': 'age', 'dataTypeName': 'Int32', 'databaseTypeName': 'Int32', 'isValueType': True, 'isAsterisk': True}, {'tableName': 'student', 'tableAlias': '', 'columnName': 'money', 'displayName': 'money', 'dataTypeName': 'Single', 'databaseTypeName': 'Float', 'isValueType': True, 'isAsterisk': True}], 'isBasic': True, 'basicDatabaseTableName': 'student', 'querySql': 'select * from `student`', 'detail': {'actionType': 2, 'filters': [], 'sorts': [{'displayName': 'id', 'sortType': 2}], 'mapping': {'pendingDisplayNameRelativeVariable': None, 'ioMappings': [{'displayName': 'name', 'relativeVariable': 'A12', 'dataType': 16384, 'order': 2}, {'displayName': 'age', 'relativeVariable': 'A2', 'dataType': 2, 'order': 3}, {'displayName': 'money', 'relativeVariable': 'A10', 'dataType': 512, 'order': 4}], 'innerMappings': [{'displayName': 'time', 'relativeVariable': 'aa16', 'dataType': 8192, 'order': 1}], 'systemMappings': []}}, 'action': {'actionType': 2, 'mainSql': 'insert into `student` (`name`,`age`,`money`,`time`) values ({0},{1},{2},{3})', 'sortSql': '`id` desc', 'filterSql': '', 'mainSqlParams': [{'key': 'A12', 'value': False}, {'key': 'A2', 'value': True}, {'key': 'A10', 'value': True}, {'key': 'aa16', 'value': False}], 'filterSqlParams': [], 'assignment': None}, 'status': 1, 'prevStatus': 0, 'lastErrorMsg': None, 'lastErrorDateTime': None}
[2024-01-16 05:48:09,153] logger_util.py->write_log line:61 [INFO] 接口请求成功！
[2024-01-16 05:48:09,153] logger_util.py->write_log line:61 [INFO] 
-------------接口请求结束-----------

[2024-01-16 05:48:11,172] logger_util.py->error_log line:65 [INFO] 发送请求异常：异常信息: Traceback (most recent call last):
  File "E:\Project_python\api_cms\common\requests_util.py", line 316, in send_request
    kwargs[key] = self.replace_load(value)
  File "E:\Project_python\api_cms\common\requests_util.py", line 140, in replace_load
    new_value = getattr(DubugTalk(), func_name)(*args_value.split(','))
  File "E:\Project_python\api_cms\debug_talk.py", line 26, in get_extract_data
    return read_extract_file(node_name)
  File "E:\Project_python\api_cms\common\yaml_util.py", line 19, in read_extract_file
    return value[one_node]
KeyError: 'Alarm_Point_ID'

[2024-01-16 05:48:11,172] logger_util.py->error_log line:65 [INFO] 分析YAML文件异常：异常信息: Traceback (most recent call last):
  File "E:\Project_python\api_cms\common\requests_util.py", line 316, in send_request
    kwargs[key] = self.replace_load(value)
  File "E:\Project_python\api_cms\common\requests_util.py", line 140, in replace_load
    new_value = getattr(DubugTalk(), func_name)(*args_value.split(','))
  File "E:\Project_python\api_cms\debug_talk.py", line 26, in get_extract_data
    return read_extract_file(node_name)
  File "E:\Project_python\api_cms\common\yaml_util.py", line 19, in read_extract_file
    return value[one_node]
KeyError: 'Alarm_Point_ID'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\Project_python\api_cms\common\requests_util.py", line 185, in analysis_yaml
    res = self.send_request(name =name,method=method,
  File "E:\Project_python\api_cms\common\requests_util.py", line 335, in send_request
    error_log("发送请求异常：异常信息: %s" % str(traceback.format_exc()))
  File "E:\Project_python\api_cms\common\logger_util.py", line 66, in error_log
    raise Exception(log_message)
Exception: 发送请求异常：异常信息: Traceback (most recent call last):
  File "E:\Project_python\api_cms\common\requests_util.py", line 316, in send_request
    kwargs[key] = self.replace_load(value)
  File "E:\Project_python\api_cms\common\requests_util.py", line 140, in replace_load
    new_value = getattr(DubugTalk(), func_name)(*args_value.split(','))
  File "E:\Project_python\api_cms\debug_talk.py", line 26, in get_extract_data
    return read_extract_file(node_name)
  File "E:\Project_python\api_cms\common\yaml_util.py", line 19, in read_extract_file
    return value[one_node]
KeyError: 'Alarm_Point_ID'


[2024-01-16 05:48:11,211] logger_util.py->error_log line:65 [INFO] 发送请求异常：异常信息: Traceback (most recent call last):
  File "E:\Project_python\api_cms\common\requests_util.py", line 312, in send_request
    self.last_headers = self.replace_load(headers)
  File "E:\Project_python\api_cms\common\requests_util.py", line 140, in replace_load
    new_value = getattr(DubugTalk(), func_name)(*args_value.split(','))
  File "E:\Project_python\api_cms\debug_talk.py", line 26, in get_extract_data
    return read_extract_file(node_name)
  File "E:\Project_python\api_cms\common\yaml_util.py", line 19, in read_extract_file
    return value[one_node]
KeyError: 'Authorization'

[2024-01-16 05:48:11,211] logger_util.py->error_log line:65 [INFO] 分析YAML文件异常：异常信息: Traceback (most recent call last):
  File "E:\Project_python\api_cms\common\requests_util.py", line 312, in send_request
    self.last_headers = self.replace_load(headers)
  File "E:\Project_python\api_cms\common\requests_util.py", line 140, in replace_load
    new_value = getattr(DubugTalk(), func_name)(*args_value.split(','))
  File "E:\Project_python\api_cms\debug_talk.py", line 26, in get_extract_data
    return read_extract_file(node_name)
  File "E:\Project_python\api_cms\common\yaml_util.py", line 19, in read_extract_file
    return value[one_node]
KeyError: 'Authorization'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\Project_python\api_cms\common\requests_util.py", line 185, in analysis_yaml
    res = self.send_request(name =name,method=method,
  File "E:\Project_python\api_cms\common\requests_util.py", line 335, in send_request
    error_log("发送请求异常：异常信息: %s" % str(traceback.format_exc()))
  File "E:\Project_python\api_cms\common\logger_util.py", line 66, in error_log
    raise Exception(log_message)
Exception: 发送请求异常：异常信息: Traceback (most recent call last):
  File "E:\Project_python\api_cms\common\requests_util.py", line 312, in send_request
    self.last_headers = self.replace_load(headers)
  File "E:\Project_python\api_cms\common\requests_util.py", line 140, in replace_load
    new_value = getattr(DubugTalk(), func_name)(*args_value.split(','))
  File "E:\Project_python\api_cms\debug_talk.py", line 26, in get_extract_data
    return read_extract_file(node_name)
  File "E:\Project_python\api_cms\common\yaml_util.py", line 19, in read_extract_file
    return value[one_node]
KeyError: 'Authorization'


[2024-01-16 05:48:11,251] logger_util.py->error_log line:65 [INFO] 发送请求异常：异常信息: Traceback (most recent call last):
  File "E:\Project_python\api_cms\common\requests_util.py", line 312, in send_request
    self.last_headers = self.replace_load(headers)
  File "E:\Project_python\api_cms\common\requests_util.py", line 140, in replace_load
    new_value = getattr(DubugTalk(), func_name)(*args_value.split(','))
  File "E:\Project_python\api_cms\debug_talk.py", line 26, in get_extract_data
    return read_extract_file(node_name)
  File "E:\Project_python\api_cms\common\yaml_util.py", line 19, in read_extract_file
    return value[one_node]
KeyError: 'Authorization'

[2024-01-16 05:48:11,251] logger_util.py->error_log line:65 [INFO] 分析YAML文件异常：异常信息: Traceback (most recent call last):
  File "E:\Project_python\api_cms\common\requests_util.py", line 312, in send_request
    self.last_headers = self.replace_load(headers)
  File "E:\Project_python\api_cms\common\requests_util.py", line 140, in replace_load
    new_value = getattr(DubugTalk(), func_name)(*args_value.split(','))
  File "E:\Project_python\api_cms\debug_talk.py", line 26, in get_extract_data
    return read_extract_file(node_name)
  File "E:\Project_python\api_cms\common\yaml_util.py", line 19, in read_extract_file
    return value[one_node]
KeyError: 'Authorization'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\Project_python\api_cms\common\requests_util.py", line 185, in analysis_yaml
    res = self.send_request(name =name,method=method,
  File "E:\Project_python\api_cms\common\requests_util.py", line 335, in send_request
    error_log("发送请求异常：异常信息: %s" % str(traceback.format_exc()))
  File "E:\Project_python\api_cms\common\logger_util.py", line 66, in error_log
    raise Exception(log_message)
Exception: 发送请求异常：异常信息: Traceback (most recent call last):
  File "E:\Project_python\api_cms\common\requests_util.py", line 312, in send_request
    self.last_headers = self.replace_load(headers)
  File "E:\Project_python\api_cms\common\requests_util.py", line 140, in replace_load
    new_value = getattr(DubugTalk(), func_name)(*args_value.split(','))
  File "E:\Project_python\api_cms\debug_talk.py", line 26, in get_extract_data
    return read_extract_file(node_name)
  File "E:\Project_python\api_cms\common\yaml_util.py", line 19, in read_extract_file
    return value[one_node]
KeyError: 'Authorization'


[2024-01-16 05:48:11,289] logger_util.py->write_log line:61 [INFO] 
-------------接口请求开始-----------
[2024-01-16 05:48:11,290] logger_util.py->write_log line:61 [INFO] 接口名称：刷新-报警触发-插入
[2024-01-16 05:48:11,290] logger_util.py->write_log line:61 [INFO] 接口方式：get
[2024-01-16 05:48:11,290] logger_util.py->write_log line:61 [INFO] 接口路径：http://127.0.0.1:18000/api/v1/connection/table/10/preview
[2024-01-16 05:48:11,290] logger_util.py->write_log line:61 [INFO] 请求头：{'X-Project': '67ebccb4a3b44b1a8a7df3f964ccbac7'}
[2024-01-16 05:48:11,290] logger_util.py->write_log line:61 [INFO] 文件上传：None
[2024-01-16 05:48:11,299] logger_util.py->error_log line:65 [INFO] 断言失败：返回结果中不存在：age
[2024-01-16 05:48:11,299] logger_util.py->write_log line:61 [INFO] 实际结果：{'status': 1, 'lastErrorMsg': None, 'total': 0, 'headers': ['id', 'time', 'name', 'age', 'money'], 'data': []}
[2024-01-16 05:48:11,299] logger_util.py->write_log line:61 [INFO] 接口请求失败！
[2024-01-16 05:48:11,299] logger_util.py->write_log line:61 [INFO] -------------接口请求结束-----------

[2024-01-16 05:48:11,299] logger_util.py->error_log line:65 [INFO] 断言异常：异常信息: Traceback (most recent call last):
  File "E:\Project_python\api_cms\common\requests_util.py", line 384, in validate_result
    error_log("断言失败：返回结果中不存在："+assert_key)
  File "E:\Project_python\api_cms\common\logger_util.py", line 66, in error_log
    raise Exception(log_message)
Exception: 断言失败：返回结果中不存在：age

[2024-01-16 05:48:11,300] logger_util.py->error_log line:65 [INFO] 分析YAML文件异常：异常信息: Traceback (most recent call last):
  File "E:\Project_python\api_cms\common\requests_util.py", line 384, in validate_result
    error_log("断言失败：返回结果中不存在："+assert_key)
  File "E:\Project_python\api_cms\common\logger_util.py", line 66, in error_log
    raise Exception(log_message)
Exception: 断言失败：返回结果中不存在：age

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\Project_python\api_cms\common\requests_util.py", line 248, in analysis_yaml
    self.validate_result(yq_result, return_data, status_code)
  File "E:\Project_python\api_cms\common\requests_util.py", line 448, in validate_result
    error_log("断言异常：异常信息: %s" % str(traceback.format_exc()))
  File "E:\Project_python\api_cms\common\logger_util.py", line 66, in error_log
    raise Exception(log_message)
Exception: 断言异常：异常信息: Traceback (most recent call last):
  File "E:\Project_python\api_cms\common\requests_util.py", line 384, in validate_result
    error_log("断言失败：返回结果中不存在："+assert_key)
  File "E:\Project_python\api_cms\common\logger_util.py", line 66, in error_log
    raise Exception(log_message)
Exception: 断言失败：返回结果中不存在：age


